In [ ]:
import pandas as pd

df = pd.read_excel("./2017_Batch.xlsx")
df.head()

,SL.NO.,STUDENT'S COLLEGE ID,DEPARTMENT (ABBR.),GENDER (M/F),AGE (IN YRS.),NAME OF EXAMINATION - CLASS X,NAME OF BOARD - CLASS X,NAME OF SCHOOL(IN FULL)-CLASS X,SUBJECT COMINATION (DO NOT USE ABBR.)-CLASS X,MEDIUM OF INSTRUCTION-CLASS X,...,NAME OF THE ORGANIZATION,DURATION (FROM DD/MM/YYYY TO DD/MM/YYYY),ANY SEMINARS/WORKSHOPS ATTENDED,"WORK EXPERIENCE, IF ANY (MONTHS / YEARS AS APPLICABLE)",NAME OF THE ORGANIZATION SERVED - WORK EXPERIENCE,ACHIEVEMENTS (ACADEMIC),ACHIEVEMENTS (NON ACADEMIC),CERTIFICATIONS (ACADEMIC),CERTIFICATIONS (NON ACADEMIC),PERMANENT LOCATION (STATE)
0,1,1.310905e+09,AEIE,F,21,I.C.S.E,COUNCIL FOR THE INDIAN SCHOOL CERTIFICATE EXAM...,RAM MOHAN MISSION HIGH SCHOOL,"ENGLISH, BENGALI, ENVIRONMENTAL EDUCATION, HIS...",ENGLISH,...,IIATCA,04/07/2016--16/07/2016,NaN,NaN,NaN,NaN,NaN,"VT - MEJIA THERMAL POWER STATION ,DVC",PAINTING,WEST BENGAL
1,2,1.310905e+09,AEIE,F,21,"SECONDARY SCHOOL EXAMINATION,2011","B.S.E.B,PATNA",GIRLS HIGH SCHOOL,"HINDI,SANSKRIT,MATHEMATICS,SCIENCE,SOCIAL SCIE...",HINDI,...,IIATCA,04/07/2016--16/07/2016,NaN,NaN,NaN,NaN,NaN,PROJECT ON INSTRUMENTATION &CONTROL SYSTEM,NaN,BIHAR
2,3,1.310905e+09,AEIE,M,20,ALL INDIA SENIOR SECONDARY EXAMINATION,CENTRAL BOARD OF SECONDARY EDUCATION,"J L M MEMORIAL SR. SEC. SCHOOL DIGWADIH, DHANBAD","HINDI COURSE-A, MATHEMATICS, SCIENCE, SOCIAL S...",ENGLISH,...,IIATCA,04/07/2016--16/07/2016,NaN,NaN,NaN,NaN,NaN,VOCATIONAL TRAINING AT HEC RANCHI,NaN,JHARKHAND
3,4,1.310905e+09,AEIE,F,21,MADHYAMIK PARIKSHA,WEST BENGAL BOARD OF SECONDARY EDUCATION,BIDYA BHARATI GIRLS' HIGH SCHOOL,"BENGALI,ENGLISH, MATHEMATICS,PHYSICAL SCIENCE,...",ENGLISH,...,IIATCA,04/07/2016--16/07/2016,CAMPUS TO CORPORATE' BY ISA(KOLKATA SECTION),NaN,NaN,NaN,NaN,VACATIONAL TRAINING AT CESC LIMITED; PROJECT T...,"SITAR (2ND YEAR), ARTS(completed 4th year)",WEST BENGAL
4,5,1.310905e+09,AEIE,F,21,I.C.S.E,COUNCIL FOR THE INDIAN SCHOOL CERTIFICATE EXAM...,"MOUNT ASSISI SCHOOL, BHAGALPUR","ENGLISH,HINDI,ENVIRONMENTAL EDUCATION,HISTORY,...",ENGLISH,...,"NTPC,KAHALGAON",15/06/2016-14/07/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIHAR

In [ ]:
df.shape

(671, 64)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 64 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   SL.NO.                                                  671 non-null    int64
 1   STUDENT'S COLLEGE ID                                    670 non-null    float64
 2   DEPARTMENT (ABBR.)                                      671 non-null    object
 3   GENDER (M/F)                                            671 non-null    object
 4   AGE (IN YRS.)                                           671 non-null    object
 5   NAME OF EXAMINATION - CLASS X                           671 non-null    object
 6   NAME OF BOARD - CLASS X                                 671 non-null    object
 7   NAME OF SCHOOL(IN FULL)-CLASS X                         668 non-null    object
 8   SUBJECT COMINATION (DO NOT USE ABBR.)-CLASS X           668 non-null    object
 9   MEDIUM OF INSTRUCTION-CLASS X                           669 non-null    object
 10  Y.O.P - CLASS X                                         670 non-null    float64
 11  STANDARD % OF CLASS X                                   666 non-null    object
 12  ACTUAL % OF CLASS X                                     666 non-null    object
 13  TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS X     636 non-null    object
 14  TOTAL MARKS OF EXAM APPEARED IN CLASS X                 645 non-null    object
 15  NAME OF EXAMINATION - CLASS XII                         622 non-null    object
 16  NAME OF BOARD/COUNCIL - CLASS XII                       621 non-null    object
 17  NAME OF SCHOOL(IN FULL) - CLASS XII                     620 non-null    object
 18  SUBJECT COMINATION (DO NOT USE ABBR.) - CLASS XII       620 non-null    object
 19  MEDIUM OF INSTRUCTION - CLASS XII                       621 non-null    object
 20  Y.O.P - CLASS XII                                       621 non-null    float64
 21  STANDARD % OF CLASS XII                                 618 non-null    float64
 22  ACTUAL % OF CLASS XII                                   620 non-null    float64
 23  TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS XII   621 non-null    object
 24  TOTAL MARKS OF EXAM APPEARED IN CLASS XII               619 non-null    float64
 25  DIPLOMA STREAM                                          98 non-null     object
 26  DIPLOMA UNIVERSITY/BOARD/COUNCIL (IN FULL)              94 non-null     object
 27  NAME OF INSTITUTE (IN FULL) - DIPLOMA                   94 non-null     object
 28  MEDIUM OF INSTRUCTION- DIPLOMA                          92 non-null     object
 29  Y.O.P - DIPLOMA                                         93 non-null     object
 30  DIPLOMA AGGREGATE MARKS %                               93 non-null     object
 31  NAME OF JOINT ENTRANCE (WBJEE/JEE-MAINS/JELET ETC.)     668 non-null    object
 32  ENTRANCE RANK(OVERALL ALL INDIA RANK)                   119 non-null    object
 33  ENTRANCE RANK(STATE RANK)                               621 non-null    object
 34  YEAR OF JOINT ENTRANCE EXAM                             663 non-null    float64
 35  CURRENT COURSE                                          670 non-null    object
 36  CURRENT STREAM                                          670 non-null    object
 37  YEAR OF ENTRY                                           670 non-null    float64
 38  YEAR OF PASSING                                         665 non-null    float64
 39  MEDIUM OF INSTRUCTION                                   667 non-null    object
 40  SEM 1                                                   582 non-null    float64
 41  SEM 2                                                   581 non-null    float64
 42  SEM 3                                                   662 non-null    object
 43  SEM 4                                                   656 non-null    float64
 44  SEM 5                                                   656 non-null    float64
 45  SEM AVG                                                 645 non-null    float64
 46  ANY BACKLOG(S) IN CURRENT COURSE(YES/NO)                554 non-null    object
 47  IF YES, MENTION NUMBER OF BACKLOG(S)                    156 non-null    object
 48  OVERALL YEAR GAP(S) IN ACADEMIC CAREER (YES/NO)         562 non-null    object
 49  IF YES, MENTION THE DURATION(S) (YYYY-YYYY)             259 non-null    object
 50  TOTAL GAP IN YEAR(S)                                    265 non-null    object
 51  CORE TECHNICAL STRENGTH                                 636 non-null    object
 52  COMPUTER LANGUAGES KNOWN                                605 non-null    object
 53  PROJECT TITLE- INDUSTRIAL TRAINING/ V.T./ INTERNSHIP    278 non-null    object
 54  NAME OF THE ORGANIZATION                                273 non-null    object
 55  DURATION (FROM DD/MM/YYYY TO DD/MM/YYYY)                271 non-null    object
 56  ANY SEMINARS/WORKSHOPS ATTENDED                         255 non-null    object
 57  WORK EXPERIENCE, IF ANY (MONTHS / YEARS AS APPLICABLE)  36 non-null     object
 58  NAME OF THE ORGANIZATION SERVED - WORK EXPERIENCE       22 non-null     object
 59  ACHIEVEMENTS (ACADEMIC)                                 225 non-null    object
 60  ACHIEVEMENTS (NON ACADEMIC)                             236 non-null    object
 61  CERTIFICATIONS (ACADEMIC)                               352 non-null    object
 62  CERTIFICATIONS (NON ACADEMIC)                           235 non-null    object
 63  PERMANENT LOCATION (STATE)                              668 non-null    object
dtypes: float64(14), int64(1), object(49)
memory usage: 335.6+ KB

In [ ]:
df.isna()

,SL.NO.,STUDENT'S COLLEGE ID,DEPARTMENT (ABBR.),GENDER (M/F),AGE (IN YRS.),NAME OF EXAMINATION - CLASS X,NAME OF BOARD - CLASS X,NAME OF SCHOOL(IN FULL)-CLASS X,SUBJECT COMINATION (DO NOT USE ABBR.)-CLASS X,MEDIUM OF INSTRUCTION-CLASS X,...,NAME OF THE ORGANIZATION,DURATION (FROM DD/MM/YYYY TO DD/MM/YYYY),ANY SEMINARS/WORKSHOPS ATTENDED,"WORK EXPERIENCE, IF ANY (MONTHS / YEARS AS APPLICABLE)",NAME OF THE ORGANIZATION SERVED - WORK EXPERIENCE,ACHIEVEMENTS (ACADEMIC),ACHIEVEMENTS (NON ACADEMIC),CERTIFICATIONS (ACADEMIC),CERTIFICATIONS (NON ACADEMIC),PERMANENT LOCATION (STATE)
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,False
667,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,True,True,False
668,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,False,True,False
669,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,False,True,False,False
670,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,False

In [ ]:
df.isna().sum().sum()

np.int64(11110)

In [ ]:
# df=df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 64 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   SL.NO.                                                  671 non-null    int64
 1   STUDENT'S COLLEGE ID                                    670 non-null    float64
 2   DEPARTMENT (ABBR.)                                      671 non-null    object
 3   GENDER (M/F)                                            671 non-null    object
 4   AGE (IN YRS.)                                           671 non-null    object
 5   NAME OF EXAMINATION - CLASS X                           671 non-null    object
 6   NAME OF BOARD - CLASS X                                 671 non-null    object
 7   NAME OF SCHOOL(IN FULL)-CLASS X                         668 non-null    object
 8   SUBJECT COMINATION (DO NOT USE ABBR.)-CLASS X           668 non-null    object
 9   MEDIUM OF INSTRUCTION-CLASS X                           669 non-null    object
 10  Y.O.P - CLASS X                                         670 non-null    float64
 11  STANDARD % OF CLASS X                                   666 non-null    object
 12  ACTUAL % OF CLASS X                                     666 non-null    object
 13  TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS X     636 non-null    object
 14  TOTAL MARKS OF EXAM APPEARED IN CLASS X                 645 non-null    object
 15  NAME OF EXAMINATION - CLASS XII                         622 non-null    object
 16  NAME OF BOARD/COUNCIL - CLASS XII                       621 non-null    object
 17  NAME OF SCHOOL(IN FULL) - CLASS XII                     620 non-null    object
 18  SUBJECT COMINATION (DO NOT USE ABBR.) - CLASS XII       620 non-null    object
 19  MEDIUM OF INSTRUCTION - CLASS XII                       621 non-null    object
 20  Y.O.P - CLASS XII                                       621 non-null    float64
 21  STANDARD % OF CLASS XII                                 618 non-null    float64
 22  ACTUAL % OF CLASS XII                                   620 non-null    float64
 23  TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS XII   621 non-null    object
 24  TOTAL MARKS OF EXAM APPEARED IN CLASS XII               619 non-null    float64
 25  DIPLOMA STREAM                                          98 non-null     object
 26  DIPLOMA UNIVERSITY/BOARD/COUNCIL (IN FULL)              94 non-null     object
 27  NAME OF INSTITUTE (IN FULL) - DIPLOMA                   94 non-null     object
 28  MEDIUM OF INSTRUCTION- DIPLOMA                          92 non-null     object
 29  Y.O.P - DIPLOMA                                         93 non-null     object
 30  DIPLOMA AGGREGATE MARKS %                               93 non-null     object
 31  NAME OF JOINT ENTRANCE (WBJEE/JEE-MAINS/JELET ETC.)     668 non-null    object
 32  ENTRANCE RANK(OVERALL ALL INDIA RANK)                   119 non-null    object
 33  ENTRANCE RANK(STATE RANK)                               621 non-null    object
 34  YEAR OF JOINT ENTRANCE EXAM                             663 non-null    float64
 35  CURRENT COURSE                                          670 non-null    object
 36  CURRENT STREAM                                          670 non-null    object
 37  YEAR OF ENTRY                                           670 non-null    float64
 38  YEAR OF PASSING                                         665 non-null    float64
 39  MEDIUM OF INSTRUCTION                                   667 non-null    object
 40  SEM 1                                                   582 non-null    float64
 41  SEM 2                                                   581 non-null    float64
 42  SEM 3                                                   662 non-null    object
 43  SEM 4                                                   656 non-null    float64
 44  SEM 5                                                   656 non-null    float64
 45  SEM AVG                                                 645 non-null    float64
 46  ANY BACKLOG(S) IN CURRENT COURSE(YES/NO)                554 non-null    object
 47  IF YES, MENTION NUMBER OF BACKLOG(S)                    156 non-null    object
 48  OVERALL YEAR GAP(S) IN ACADEMIC CAREER (YES/NO)         562 non-null    object
 49  IF YES, MENTION THE DURATION(S) (YYYY-YYYY)             259 non-null    object
 50  TOTAL GAP IN YEAR(S)                                    265 non-null    object
 51  CORE TECHNICAL STRENGTH                                 636 non-null    object
 52  COMPUTER LANGUAGES KNOWN                                605 non-null    object
 53  PROJECT TITLE- INDUSTRIAL TRAINING/ V.T./ INTERNSHIP    278 non-null    object
 54  NAME OF THE ORGANIZATION                                273 non-null    object
 55  DURATION (FROM DD/MM/YYYY TO DD/MM/YYYY)                271 non-null    object
 56  ANY SEMINARS/WORKSHOPS ATTENDED                         255 non-null    object
 57  WORK EXPERIENCE, IF ANY (MONTHS / YEARS AS APPLICABLE)  36 non-null     object
 58  NAME OF THE ORGANIZATION SERVED - WORK EXPERIENCE       22 non-null     object
 59  ACHIEVEMENTS (ACADEMIC)                                 225 non-null    object
 60  ACHIEVEMENTS (NON ACADEMIC)                             236 non-null    object
 61  CERTIFICATIONS (ACADEMIC)                               352 non-null    object
 62  CERTIFICATIONS (NON ACADEMIC)                           235 non-null    object
 63  PERMANENT LOCATION (STATE)                              668 non-null    object
dtypes: float64(14), int64(1), object(49)
memory usage: 335.6+ KB

In [ ]:
df.shape

(671, 64)

In [ ]:
df.columns

Index(['SL.NO.', 'STUDENT'S COLLEGE ID', 'DEPARTMENT (ABBR.)', 'GENDER (M/F)',
       'AGE (IN YRS.)', 'NAME OF EXAMINATION - CLASS X',
       'NAME OF BOARD - CLASS X', 'NAME OF SCHOOL(IN FULL)-CLASS X',
       'SUBJECT COMINATION (DO NOT USE ABBR.)-CLASS X',
       'MEDIUM OF INSTRUCTION-CLASS X', 'Y.O.P - CLASS X',
       'STANDARD % OF CLASS X', 'ACTUAL % OF CLASS X',
       'TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS X',
       'TOTAL MARKS OF EXAM APPEARED IN CLASS X',
       'NAME OF EXAMINATION - CLASS XII', 'NAME OF BOARD/COUNCIL - CLASS XII',
       'NAME OF SCHOOL(IN FULL) - CLASS XII',
       'SUBJECT COMINATION (DO NOT USE ABBR.) - CLASS XII',
       'MEDIUM OF INSTRUCTION - CLASS XII', 'Y.O.P - CLASS XII',
       'STANDARD % OF CLASS XII', 'ACTUAL % OF CLASS XII',
       'TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS XII',
       'TOTAL MARKS OF EXAM APPEARED IN CLASS XII', 'DIPLOMA STREAM',
       'DIPLOMA UNIVERSITY/BOARD/COUNCIL (IN FULL)',
       'NAME OF INSTITUTE (IN FULL) - DIPLOMA',
       'MEDIUM OF INSTRUCTION- DIPLOMA', 'Y.O.P - DIPLOMA',
       'DIPLOMA AGGREGATE MARKS % ',
       'NAME OF JOINT ENTRANCE (WBJEE/JEE-MAINS/JELET ETC.)',
       'ENTRANCE RANK(OVERALL ALL INDIA RANK)', 'ENTRANCE RANK(STATE RANK)',
       'YEAR OF JOINT ENTRANCE EXAM', 'CURRENT COURSE', 'CURRENT STREAM',
       'YEAR OF ENTRY', 'YEAR OF PASSING', 'MEDIUM OF INSTRUCTION', 'SEM 1',
       'SEM 2', 'SEM 3', 'SEM 4', 'SEM 5', 'SEM AVG',
       'ANY BACKLOG(S) IN CURRENT COURSE(YES/NO)',
       'IF YES, MENTION NUMBER OF BACKLOG(S)',
       'OVERALL YEAR GAP(S) IN ACADEMIC CAREER (YES/NO)',
       'IF YES, MENTION THE DURATION(S) (YYYY-YYYY)', 'TOTAL GAP IN YEAR(S)',
       'CORE TECHNICAL STRENGTH', 'COMPUTER LANGUAGES KNOWN',
       'PROJECT TITLE- INDUSTRIAL TRAINING/ V.T./ INTERNSHIP',
       'NAME OF THE ORGANIZATION', 'DURATION (FROM DD/MM/YYYY TO DD/MM/YYYY)',
       'ANY SEMINARS/WORKSHOPS ATTENDED',
       'WORK EXPERIENCE, IF ANY (MONTHS / YEARS AS APPLICABLE)',
       'NAME OF THE ORGANIZATION SERVED - WORK EXPERIENCE',
       'ACHIEVEMENTS (ACADEMIC) ', 'ACHIEVEMENTS (NON ACADEMIC) ',
       'CERTIFICATIONS (ACADEMIC)', 'CERTIFICATIONS (NON ACADEMIC)',
       'PERMANENT LOCATION (STATE)'],
      dtype='object')

SEM AVG is directly calculated from SEM 1 – 5, this creates data leakage. so we are only using marks from sem 1-3

In [ ]:
feature_cols = [
    'TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS X',
    'TOTAL MARKS OF EXAM APPEARED IN CLASS X',
    'TOTAL MARKS OBTAINED IN ALL THE SUBJECTS IN CLASS XII',
    'DIPLOMA AGGREGATE MARKS % ',
    'ENTRANCE RANK(OVERALL ALL INDIA RANK)',
    'SEM 1',
    'SEM 2',
    'SEM 3'
]

X = df[feature_cols].copy()
y = df['SEM AVG'].copy()

In [ ]:
import numpy as np
import re

X = X.replace(['N.A', '-', 'NA', 'na', ''], np.nan)
y = y.replace(['N.A', '-', 'NA', 'na', ''], np.nan)

def extract_number(x):
    if isinstance(x, str):
        m = re.search(r'(\d+(\.\d+)?)', x)
        return float(m.group(1)) if m else np.nan
    return x

X = X.applymap(extract_number)
y = y.apply(extract_number)

/tmp/ipython-input-568320121.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X = X.replace(['N.A', '-', 'NA', 'na', ''], np.nan)
/tmp/ipython-input-568320121.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X = X.applymap(extract_number)

In [ ]:
mask = y.notna()
X = X.loc[mask]
y = y.loc[mask]

In [ ]:
X.shape

(645, 8)

In [ ]:
import re

def extract_number(x):
    if isinstance(x, str):
        m = re.search(r'(\d+(\.\d+)?)', x)
        return float(m.group(1)) if m else None
    return x

X = X.applymap(extract_number)

/tmp/ipython-input-424674936.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X = X.applymap(extract_number)


Data is split into 5 folds

4 folds → training

1 fold → testing

This repeats 5 times

You get 5 test results

In [ ]:
from sklearn.model_selection import KFold, cross_validate
kf = KFold(n_splits=5, shuffle=True, random_state=42)

In [ ]:
!pip install xgboost catboost lightgbm

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.1.3)
Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.3)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.9 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [ ]:
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor, HistGradientBoostingRegressor
from sklearn.linear_model import Ridge

In [ ]:
models = {
    "Random Forest": RandomForestRegressor(random_state=42),

    "Extra Trees": ExtraTreesRegressor(random_state=42),

    "XGBoost": XGBRegressor(
        random_state=42,
        verbosity=0
    ),

    "CatBoost": CatBoostRegressor(
        random_state=42,
        verbose=0
    ),



    "SVR": SVR(),

    "KNN": KNeighborsRegressor(),

    "AdaBoost": AdaBoostRegressor(random_state=42),

    "HistGB": HistGradientBoostingRegressor(random_state=42),

    "Ridge": Ridge()
}

In [ ]:
mask = y.notna()

X = X[mask]
y = y[mask]

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

RMSE → average prediction error (strong penalty)

MAE → average simple error

MSE → squared error

R² → goodness of fit

MAPE → percentage error

In [ ]:
from sklearn.model_selection import cross_validate
import numpy as np

scoring = {
    'rmse': 'neg_root_mean_squared_error',
    'mae': 'neg_mean_absolute_error',
    'mse': 'neg_mean_squared_error',
    'r2': 'r2',
    'mape': 'neg_mean_absolute_percentage_error'
}

for name, model in models.items():

    scores = cross_validate(
        model,
        X,
        y,
        cv=kf,
        scoring=scoring
    )

    rmse = -scores['test_rmse'].mean()
    mae  = -scores['test_mae'].mean()
    mse  = -scores['test_mse'].mean()
    mape = -scores['test_mape'].mean()
    r2   = scores['test_r2'].mean()

    print(name)
    print("RMSE :", rmse)
    print("MAE  :", mae)
    print("MSE  :", mse)
    print("MAPE :", mape)
    print("R2   :", r2)
    print("------------------")

Random Forest
RMSE : 0.280249428801718
MAE  : 0.19767597932816555
MSE  : 0.0797882037073557
MAPE : 0.028719674819303632
R2   : 0.8926907473804503
------------------
Extra Trees
RMSE : 0.26587158460725596
MAE  : 0.18701608268733858
MSE  : 0.07218965940823427
MAPE : 0.02704910469684777
R2   : 0.9038372367530805
------------------
XGBoost
RMSE : 0.2826605346404844
MAE  : 0.19992247961473092
MSE  : 0.08073059169435824
MAPE : 0.028931044355569445
R2   : 0.8909071221997953
------------------
CatBoost
RMSE : 0.2657074398243001
MAE  : 0.1871448362415293
MSE  : 0.07191746035442173
MAPE : 0.027074897526799774
R2   : 0.9036162359367008
------------------
SVR
RMSE : 0.8538841923008125
MAE  : 0.6818875420364008
MSE  : 0.7355776604395546
MAPE : 0.09750001011486728
R2   : 0.007127367800185058
------------------
KNN
RMSE : 0.7572670162155952
MAE  : 0.5924640826873385
MSE  : 0.5787590887579672
MAPE : 0.08346633280365989
R2   : 0.2165866515554904
------------------
AdaBoost
RMSE : 0.3146281788135773
MAE  : 0.23725315272985775
MSE  : 0.10055384222992717
MAPE : 0.03381921272690787
R2   : 0.864996819585896
------------------
HistGB
RMSE : 0.27887872324225904
MAE  : 0.19925264208739088
MSE  : 0.07894055013197745
MAPE : 0.02883002709600082
R2   : 0.8936885699421377
------------------
Ridge
RMSE : 0.3093185569265059
MAE  : 0.21148728407546882
MSE  : 0.09860262857334821
MAPE : 0.030467653361635195
R2   : 0.8668823245223596
------------------

hypertunning best 5 models.


Hyperparameter tuning is the process of selecting the optimal model configuration parameters in order to improve predictive performance.
Trying different model settings and picking the one that gives the lowest RMSE.

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.3)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 8.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [ ]:
import optuna
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor

def objective_et(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 25),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "random_state": 42
    }

    model = ExtraTreesRegressor(**params)

    scores = cross_val_score(
        model, X, y,
        cv=kf,
        scoring="neg_root_mean_squared_error"
    )

    return -scores.mean()

In [ ]:
study_et = optuna.create_study(direction="minimize")
study_et.optimize(objective_et, n_trials=100)

print("Extra Trees best RMSE:", study_et.best_value)
print(study_et.best_params)

[I 2026-02-17 08:29:49,345] A new study created in memory with name: no-name-385c6a1f-419f-4cb0-96d7-760a32ba8537
[I 2026-02-17 08:29:50,440] Trial 0 finished with value: 0.30099884384769776 and parameters: {'n_estimators': 257, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 0 with value: 0.30099884384769776.
[I 2026-02-17 08:29:55,869] Trial 1 finished with value: 0.26442802367251705 and parameters: {'n_estimators': 372, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 1 with value: 0.26442802367251705.
[I 2026-02-17 08:29:58,858] Trial 2 finished with value: 0.2594569996308294 and parameters: {'n_estimators': 266, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 2 with value: 0.2594569996308294.
[I 2026-02-17 08:30:02,920] Trial 3 finished with value: 0.2610162166990647 and parameters: {'n_estimators': 293, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 2 with value: 0.2594569996308294.
[I 2026-02-17 08:30:05,542] Trial 4 finished with value: 0.26241143850891546 and parameters: {'n_estimators': 181, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 2 with value: 0.2594569996308294.
[I 2026-02-17 08:30:07,878] Trial 5 finished with value: 0.2614428780451289 and parameters: {'n_estimators': 173, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 2 with value: 0.2594569996308294.
[I 2026-02-17 08:30:10,639] Trial 6 finished with value: 0.2603657394292597 and parameters: {'n_estimators': 397, 'max_depth': 23, 'min_samples_split': 6}. Best is trial 2 with value: 0.2594569996308294.
[I 2026-02-17 08:30:11,272] Trial 7 finished with value: 0.262012610467213 and parameters: {'n_estimators': 110, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 2 with value: 0.2594569996308294.
[I 2026-02-17 08:30:13,335] Trial 8 finished with value: 0.25877133087637444 and parameters: {'n_estimators': 380, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:14,264] Trial 9 finished with value: 0.2620702258783942 and parameters: {'n_estimators': 154, 'max_depth': 22, 'min_samples_split': 5}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:16,283] Trial 10 finished with value: 0.25951580800499263 and parameters: {'n_estimators': 336, 'max_depth': 18, 'min_samples_split': 9}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:17,944] Trial 11 finished with value: 0.2591594076694169 and parameters: {'n_estimators': 313, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:19,369] Trial 12 finished with value: 0.2609574900793394 and parameters: {'n_estimators': 327, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:21,074] Trial 13 finished with value: 0.2590627878541728 and parameters: {'n_estimators': 336, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:22,917] Trial 14 finished with value: 0.2588433626109906 and parameters: {'n_estimators': 367, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:25,006] Trial 15 finished with value: 0.25958020422125755 and parameters: {'n_estimators': 396, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:26,187] Trial 16 finished with value: 0.2591390385884795 and parameters: {'n_estimators': 223, 'max_depth': 21, 'min_samples_split': 8}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:28,505] Trial 17 finished with value: 0.25881223476666626 and parameters: {'n_estimators': 366, 'max_depth': 25, 'min_samples_split': 10}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:30,472] Trial 18 finished with value: 0.2595953530588637 and parameters: {'n_estimators': 360, 'max_depth': 25, 'min_samples_split': 7}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:31,463] Trial 19 finished with value: 0.3539817764724086 and parameters: {'n_estimators': 294, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:32,649] Trial 20 finished with value: 0.2592511397050449 and parameters: {'n_estimators': 225, 'max_depth': 20, 'min_samples_split': 8}. Best is trial 8 with value: 0.25877133087637444.
[I 2026-02-17 08:30:34,491] Trial 21 finished with value: 0.2586405794579098 and parameters: {'n_estimators': 365, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:36,271] Trial 22 finished with value: 0.2587191285698186 and parameters: {'n_estimators': 355, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:38,293] Trial 23 finished with value: 0.2595728257195956 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:40,564] Trial 24 finished with value: 0.25873598514444707 and parameters: {'n_estimators': 349, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:42,230] Trial 25 finished with value: 0.25928516608040836 and parameters: {'n_estimators': 346, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:43,770] Trial 26 finished with value: 0.2588969975911921 and parameters: {'n_estimators': 299, 'max_depth': 19, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:45,417] Trial 27 finished with value: 0.2596373491757384 and parameters: {'n_estimators': 323, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:46,884] Trial 28 finished with value: 0.25951731081216517 and parameters: {'n_estimators': 269, 'max_depth': 15, 'min_samples_split': 7}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:47,838] Trial 29 finished with value: 0.26403457842533273 and parameters: {'n_estimators': 228, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:49,563] Trial 30 finished with value: 0.2587675303026097 and parameters: {'n_estimators': 349, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:51,777] Trial 31 finished with value: 0.259114953340268 and parameters: {'n_estimators': 357, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:53,668] Trial 32 finished with value: 0.25881521107332 and parameters: {'n_estimators': 378, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:55,406] Trial 33 finished with value: 0.2587675303026097 and parameters: {'n_estimators': 349, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 21 with value: 0.2586405794579098.
[I 2026-02-17 08:30:56,931] Trial 34 finished with value: 0.25858753176765625 and parameters: {'n_estimators': 310, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 34 with value: 0.25858753176765625.
[I 2026-02-17 08:30:59,146] Trial 35 finished with value: 0.2629715382736197 and parameters: {'n_estimators': 312, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 34 with value: 0.25858753176765625.
[I 2026-02-17 08:31:00,185] Trial 36 finished with value: 0.2802528092915598 and parameters: {'n_estimators': 277, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 34 with value: 0.25858753176765625.
[I 2026-02-17 08:31:02,366] Trial 37 finished with value: 0.258753479993611 and parameters: {'n_estimators': 382, 'max_depth': 10, 'min_samples_split': 8}. Best is trial 34 with value: 0.25858753176765625.
[I 2026-02-17 08:31:03,743] Trial 38 finished with value: 0.25842364101294235 and parameters: {'n_estimators': 249, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:05,194] Trial 39 finished with value: 0.2608274058052313 and parameters: {'n_estimators': 246, 'max_depth': 13, 'min_samples_split': 4}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:06,444] Trial 40 finished with value: 0.2585782191693796 and parameters: {'n_estimators': 250, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:07,666] Trial 41 finished with value: 0.2591048276581996 and parameters: {'n_estimators': 246, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:08,659] Trial 42 finished with value: 0.2589126687349543 and parameters: {'n_estimators': 197, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:10,053] Trial 43 finished with value: 0.2593760810554825 and parameters: {'n_estimators': 273, 'max_depth': 13, 'min_samples_split': 8}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:11,292] Trial 44 finished with value: 0.2587714223018899 and parameters: {'n_estimators': 256, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:12,233] Trial 45 finished with value: 0.2617276805746601 and parameters: {'n_estimators': 205, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:14,275] Trial 46 finished with value: 0.26028777490659055 and parameters: {'n_estimators': 284, 'max_depth': 14, 'min_samples_split': 6}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:15,804] Trial 47 finished with value: 0.2589753053515315 and parameters: {'n_estimators': 305, 'max_depth': 18, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:16,585] Trial 48 finished with value: 0.2600894198158756 and parameters: {'n_estimators': 139, 'max_depth': 17, 'min_samples_split': 9}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:17,728] Trial 49 finished with value: 0.2592402305420084 and parameters: {'n_estimators': 235, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:19,216] Trial 50 finished with value: 0.258548536477728 and parameters: {'n_estimators': 285, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:20,681] Trial 51 finished with value: 0.2586393074498862 and parameters: {'n_estimators': 286, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:21,980] Trial 52 finished with value: 0.25862273585985995 and parameters: {'n_estimators': 255, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:23,344] Trial 53 finished with value: 0.25981806502451477 and parameters: {'n_estimators': 261, 'max_depth': 18, 'min_samples_split': 9}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:25,076] Trial 54 finished with value: 0.2586393074498862 and parameters: {'n_estimators': 286, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:26,331] Trial 55 finished with value: 0.25891972167110533 and parameters: {'n_estimators': 210, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:27,566] Trial 56 finished with value: 0.25962686528057055 and parameters: {'n_estimators': 239, 'max_depth': 20, 'min_samples_split': 9}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:28,817] Trial 57 finished with value: 0.25853398884391987 and parameters: {'n_estimators': 254, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:30,145] Trial 58 finished with value: 0.2594917516983239 and parameters: {'n_estimators': 256, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:31,233] Trial 59 finished with value: 0.2586997806387401 and parameters: {'n_estimators': 218, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:32,614] Trial 60 finished with value: 0.2595479369398093 and parameters: {'n_estimators': 266, 'max_depth': 13, 'min_samples_split': 8}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:34,027] Trial 61 finished with value: 0.2585287864374446 and parameters: {'n_estimators': 282, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 38 with value: 0.25842364101294235.
[I 2026-02-17 08:31:35,522] Trial 62 finished with value: 0.25820177200781397 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:37,583] Trial 63 finished with value: 0.2585097625967777 and parameters: {'n_estimators': 317, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:39,555] Trial 64 finished with value: 0.2583877472566879 and parameters: {'n_estimators': 323, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:41,179] Trial 65 finished with value: 0.25876217825602715 and parameters: {'n_estimators': 324, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:42,887] Trial 66 finished with value: 0.2584076311141344 and parameters: {'n_estimators': 336, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:44,582] Trial 67 finished with value: 0.259634419177977 and parameters: {'n_estimators': 337, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:46,181] Trial 68 finished with value: 0.25851786604169485 and parameters: {'n_estimators': 319, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:48,622] Trial 69 finished with value: 0.2593419517989034 and parameters: {'n_estimators': 332, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:50,213] Trial 70 finished with value: 0.2585097625967777 and parameters: {'n_estimators': 317, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:51,787] Trial 71 finished with value: 0.25851786604169485 and parameters: {'n_estimators': 319, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:53,405] Trial 72 finished with value: 0.25884325575399253 and parameters: {'n_estimators': 323, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:54,928] Trial 73 finished with value: 0.25820177200781397 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:56,427] Trial 74 finished with value: 0.2585941828637123 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:31:58,165] Trial 75 finished with value: 0.2591189947134234 and parameters: {'n_estimators': 338, 'max_depth': 15, 'min_samples_split': 9}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:00,105] Trial 76 finished with value: 0.25875912657744515 and parameters: {'n_estimators': 296, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:01,909] Trial 77 finished with value: 0.26018130286993346 and parameters: {'n_estimators': 317, 'max_depth': 14, 'min_samples_split': 5}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:03,481] Trial 78 finished with value: 0.25957066894740044 and parameters: {'n_estimators': 307, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:05,111] Trial 79 finished with value: 0.2587797167144529 and parameters: {'n_estimators': 329, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:06,659] Trial 80 finished with value: 0.2591653443029861 and parameters: {'n_estimators': 303, 'max_depth': 15, 'min_samples_split': 9}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:08,309] Trial 81 finished with value: 0.25842431982545433 and parameters: {'n_estimators': 322, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:10,102] Trial 82 finished with value: 0.2585070419719552 and parameters: {'n_estimators': 343, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:12,135] Trial 83 finished with value: 0.2585167872421968 and parameters: {'n_estimators': 345, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:13,808] Trial 84 finished with value: 0.25873133994753056 and parameters: {'n_estimators': 340, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:15,374] Trial 85 finished with value: 0.25887133486117947 and parameters: {'n_estimators': 329, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:16,933] Trial 86 finished with value: 0.25891465280336884 and parameters: {'n_estimators': 313, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:18,756] Trial 87 finished with value: 0.25867786148494654 and parameters: {'n_estimators': 369, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:20,533] Trial 88 finished with value: 0.258243773461365 and parameters: {'n_estimators': 357, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:22,704] Trial 89 finished with value: 0.2592829476450934 and parameters: {'n_estimators': 358, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:24,474] Trial 90 finished with value: 0.2586973664339055 and parameters: {'n_estimators': 354, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 62 with value: 0.25820177200781397.
[I 2026-02-17 08:32:25,952] Trial 91 finished with value: 0.25811758188635003 and parameters: {'n_estimators': 293, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 91 with value: 0.25811758188635003.
[I 2026-02-17 08:32:27,406] Trial 92 finished with value: 0.25818654330888463 and parameters: {'n_estimators': 295, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 91 with value: 0.25811758188635003.
[I 2026-02-17 08:32:28,798] Trial 93 finished with value: 0.2587171614259285 and parameters: {'n_estimators': 291, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 91 with value: 0.25811758188635003.
[I 2026-02-17 08:32:30,640] Trial 94 finished with value: 0.2583166092522299 and parameters: {'n_estimators': 378, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 91 with value: 0.25811758188635003.

Extra Trees best RMSE: 0.25811758188635003
{'n_estimators': 293, 'max_depth': 14, 'min_samples_split': 10}

In [ ]:
from catboost import CatBoostRegressor

def objective_cat(trial):

    params = {
        "iterations": trial.suggest_int("iterations", 200, 600),
        "depth": trial.suggest_int("depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "random_state": 42,
        "verbose": 0
    }

    model = CatBoostRegressor(**params)

    scores = cross_val_score(
        model, X, y,
        cv=kf,
        scoring="neg_root_mean_squared_error"
    )

    return -scores.mean()

In [ ]:
study_cat = optuna.create_study(direction="minimize")
study_cat.optimize(objective_cat, n_trials=100)

print("CatBoost best RMSE:", study_cat.best_value)
print(study_cat.best_params)

[I 2026-02-17 08:32:40,673] A new study created in memory with name: no-name-35aaa550-54fa-45d9-a9c7-e5d9509df0ae
[I 2026-02-17 08:32:43,261] Trial 0 finished with value: 0.26521672534878166 and parameters: {'iterations': 266, 'depth': 7, 'learning_rate': 0.09537288627823982}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:32:59,857] Trial 1 finished with value: 0.2810785474838272 and parameters: {'iterations': 265, 'depth': 9, 'learning_rate': 0.10293584558669266}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:02,565] Trial 2 finished with value: 0.2695310734987518 and parameters: {'iterations': 476, 'depth': 4, 'learning_rate': 0.09726631357500554}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:04,289] Trial 3 finished with value: 0.274648343887591 and parameters: {'iterations': 550, 'depth': 5, 'learning_rate': 0.11020487073107423}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:05,996] Trial 4 finished with value: 0.2702378130375958 and parameters: {'iterations': 352, 'depth': 6, 'learning_rate': 0.1272153434967705}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:23,165] Trial 5 finished with value: 0.2770063526727899 and parameters: {'iterations': 359, 'depth': 10, 'learning_rate': 0.04050550102910912}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:24,076] Trial 6 finished with value: 0.2741524353389522 and parameters: {'iterations': 370, 'depth': 4, 'learning_rate': 0.18936767184956968}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:28,186] Trial 7 finished with value: 0.2723341910770048 and parameters: {'iterations': 562, 'depth': 7, 'learning_rate': 0.107454739485039}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:29,065] Trial 8 finished with value: 0.27279449219921015 and parameters: {'iterations': 255, 'depth': 5, 'learning_rate': 0.15986146127248588}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:37,207] Trial 9 finished with value: 0.288860070763818 and parameters: {'iterations': 306, 'depth': 9, 'learning_rate': 0.012750231324650918}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:39,846] Trial 10 finished with value: 0.2686619572502041 and parameters: {'iterations': 205, 'depth': 8, 'learning_rate': 0.04611234738185224}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:43,394] Trial 11 finished with value: 0.2702134642567017 and parameters: {'iterations': 205, 'depth': 8, 'learning_rate': 0.0608900344051689}. Best is trial 0 with value: 0.26521672534878166.
[I 2026-02-17 08:33:45,047] Trial 12 finished with value: 0.26337933659724816 and parameters: {'iterations': 203, 'depth': 7, 'learning_rate': 0.06203124094942913}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:33:48,371] Trial 13 finished with value: 0.26845902853274634 and parameters: {'iterations': 446, 'depth': 7, 'learning_rate': 0.0739413446100843}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:33:50,555] Trial 14 finished with value: 0.2716515889917145 and parameters: {'iterations': 284, 'depth': 7, 'learning_rate': 0.1390947441213785}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:33:51,716] Trial 15 finished with value: 0.26735885780331703 and parameters: {'iterations': 233, 'depth': 6, 'learning_rate': 0.08332878152803366}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:33:56,680] Trial 16 finished with value: 0.26901028644461566 and parameters: {'iterations': 319, 'depth': 8, 'learning_rate': 0.029793090486201046}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:33:57,710] Trial 17 finished with value: 0.26652474736786597 and parameters: {'iterations': 201, 'depth': 6, 'learning_rate': 0.06705610430604964}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:34:08,301] Trial 18 finished with value: 0.28125213530650317 and parameters: {'iterations': 414, 'depth': 9, 'learning_rate': 0.15163478580428247}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:34:09,360] Trial 19 finished with value: 0.26400492946736676 and parameters: {'iterations': 315, 'depth': 5, 'learning_rate': 0.09076875818271095}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:34:10,385] Trial 20 finished with value: 0.26345491642441216 and parameters: {'iterations': 308, 'depth': 5, 'learning_rate': 0.05992981718030513}. Best is trial 12 with value: 0.26337933659724816.
[I 2026-02-17 08:34:11,462] Trial 21 finished with value: 0.2604138444756168 and parameters: {'iterations': 316, 'depth': 5, 'learning_rate': 0.05329998475830379}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:12,838] Trial 22 finished with value: 0.26141310920470023 and parameters: {'iterations': 400, 'depth': 5, 'learning_rate': 0.022997008831468515}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:13,793] Trial 23 finished with value: 0.26392103118128785 and parameters: {'iterations': 413, 'depth': 4, 'learning_rate': 0.017686534002098363}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:16,451] Trial 24 finished with value: 0.26446252702042317 and parameters: {'iterations': 499, 'depth': 6, 'learning_rate': 0.04521530948406409}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:18,137] Trial 25 finished with value: 0.2619247226847607 and parameters: {'iterations': 380, 'depth': 5, 'learning_rate': 0.02897216877124326}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:19,390] Trial 26 finished with value: 0.26104916697137803 and parameters: {'iterations': 395, 'depth': 5, 'learning_rate': 0.02873030285061819}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:20,421] Trial 27 finished with value: 0.26069676226785493 and parameters: {'iterations': 452, 'depth': 4, 'learning_rate': 0.028364431612865643}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:21,588] Trial 28 finished with value: 0.270990170422425 and parameters: {'iterations': 512, 'depth': 4, 'learning_rate': 0.010327658509966985}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:22,614] Trial 29 finished with value: 0.26167571819615465 and parameters: {'iterations': 449, 'depth': 4, 'learning_rate': 0.03501073414268442}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:23,612] Trial 30 finished with value: 0.26302200931490327 and parameters: {'iterations': 444, 'depth': 4, 'learning_rate': 0.05029628220601233}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:24,880] Trial 31 finished with value: 0.2616143650175685 and parameters: {'iterations': 397, 'depth': 5, 'learning_rate': 0.024712495291316333}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:26,510] Trial 32 finished with value: 0.2640942657679088 and parameters: {'iterations': 340, 'depth': 6, 'learning_rate': 0.029957908845415018}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:28,771] Trial 33 finished with value: 0.26094963282533806 and parameters: {'iterations': 479, 'depth': 5, 'learning_rate': 0.02234910300514865}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:29,944] Trial 34 finished with value: 0.2640537933974271 and parameters: {'iterations': 519, 'depth': 4, 'learning_rate': 0.05279665604931789}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:31,397] Trial 35 finished with value: 0.26974207417849755 and parameters: {'iterations': 470, 'depth': 5, 'learning_rate': 0.0764446405470749}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:34,265] Trial 36 finished with value: 0.2638589766940374 and parameters: {'iterations': 537, 'depth': 6, 'learning_rate': 0.038681267157857385}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:35,363] Trial 37 finished with value: 0.26216663793418044 and parameters: {'iterations': 486, 'depth': 4, 'learning_rate': 0.019494963503609433}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:36,719] Trial 38 finished with value: 0.26156418559571626 and parameters: {'iterations': 426, 'depth': 5, 'learning_rate': 0.039853063560599186}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:39,040] Trial 39 finished with value: 0.27565457162595824 and parameters: {'iterations': 475, 'depth': 6, 'learning_rate': 0.12249700710970557}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:40,509] Trial 40 finished with value: 0.2734533850982589 and parameters: {'iterations': 335, 'depth': 4, 'learning_rate': 0.014010028379851245}. Best is trial 21 with value: 0.2604138444756168.
[I 2026-02-17 08:34:42,356] Trial 41 finished with value: 0.2602716752742155 and parameters: {'iterations': 598, 'depth': 5, 'learning_rate': 0.02207801099833563}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:34:44,218] Trial 42 finished with value: 0.26549780035839915 and parameters: {'iterations': 599, 'depth': 5, 'learning_rate': 0.05177109546908315}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:34:46,029] Trial 43 finished with value: 0.26127241072842994 and parameters: {'iterations': 585, 'depth': 5, 'learning_rate': 0.036825470887683655}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:35:11,508] Trial 44 finished with value: 0.2804702523027191 and parameters: {'iterations': 562, 'depth': 10, 'learning_rate': 0.010177231280519963}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:35:12,466] Trial 45 finished with value: 0.27862413673492764 and parameters: {'iterations': 378, 'depth': 4, 'learning_rate': 0.1939365302345083}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:35:14,732] Trial 46 finished with value: 0.28046415974507377 and parameters: {'iterations': 458, 'depth': 5, 'learning_rate': 0.17982217937788555}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:35:16,114] Trial 47 finished with value: 0.26605975779547986 and parameters: {'iterations': 278, 'depth': 6, 'learning_rate': 0.023413858173893208}. Best is trial 41 with value: 0.2602716752742155.
[I 2026-02-17 08:35:16,955] Trial 48 finished with value: 0.2601029829224253 and parameters: {'iterations': 356, 'depth': 4, 'learning_rate': 0.031301456449289014}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:17,816] Trial 49 finished with value: 0.2615360703358621 and parameters: {'iterations': 363, 'depth': 4, 'learning_rate': 0.043282534034139265}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:18,482] Trial 50 finished with value: 0.26420932799982844 and parameters: {'iterations': 250, 'depth': 4, 'learning_rate': 0.05739717065387851}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:19,645] Trial 51 finished with value: 0.26104602488145245 and parameters: {'iterations': 348, 'depth': 5, 'learning_rate': 0.030480448946255605}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:20,526] Trial 52 finished with value: 0.26150839085445743 and parameters: {'iterations': 348, 'depth': 4, 'learning_rate': 0.03284629342196095}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:21,577] Trial 53 finished with value: 0.26801104453817154 and parameters: {'iterations': 295, 'depth': 5, 'learning_rate': 0.019619147912845573}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:23,254] Trial 54 finished with value: 0.2673148956052865 and parameters: {'iterations': 334, 'depth': 6, 'learning_rate': 0.06976130676072595}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:24,682] Trial 55 finished with value: 0.26993637486853916 and parameters: {'iterations': 431, 'depth': 5, 'learning_rate': 0.1010798668920534}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:26,260] Trial 56 finished with value: 0.26361085311889304 and parameters: {'iterations': 328, 'depth': 4, 'learning_rate': 0.04414748846708133}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:29,009] Trial 57 finished with value: 0.2713576104380241 and parameters: {'iterations': 358, 'depth': 7, 'learning_rate': 0.016553523853980935}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:30,851] Trial 58 finished with value: 0.2607937868006246 and parameters: {'iterations': 383, 'depth': 5, 'learning_rate': 0.025377413505491758}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:32,046] Trial 59 finished with value: 0.2633463862606069 and parameters: {'iterations': 381, 'depth': 4, 'learning_rate': 0.02416645396090142}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:34,549] Trial 60 finished with value: 0.2668151890904996 and parameters: {'iterations': 542, 'depth': 6, 'learning_rate': 0.049184075884739595}. Best is trial 48 with value: 0.2601029829224253.
[I 2026-02-17 08:35:35,777] Trial 61 finished with value: 0.2598089687072299 and parameters: {'iterations': 369, 'depth': 5, 'learning_rate': 0.032391273313501785}. Best is trial 61 with value: 0.2598089687072299.
[I 2026-02-17 08:35:37,993] Trial 62 finished with value: 0.26162366728112574 and parameters: {'iterations': 413, 'depth': 5, 'learning_rate': 0.03618646670811988}. Best is trial 61 with value: 0.2598089687072299.
[I 2026-02-17 08:35:39,222] Trial 63 finished with value: 0.26139564808312066 and parameters: {'iterations': 372, 'depth': 5, 'learning_rate': 0.025286317213923236}. Best is trial 61 with value: 0.2598089687072299.
[I 2026-02-17 08:35:40,150] Trial 64 finished with value: 0.2659044388425397 and parameters: {'iterations': 389, 'depth': 4, 'learning_rate': 0.017294714045426797}. Best is trial 61 with value: 0.2598089687072299.
[I 2026-02-17 08:35:41,511] Trial 65 finished with value: 0.264944442278937 and parameters: {'iterations': 429, 'depth': 5, 'learning_rate': 0.05475377775875231}. Best is trial 61 with value: 0.2598089687072299.
[I 2026-02-17 08:35:42,552] Trial 66 finished with value: 0.2597385582056418 and parameters: {'iterations': 295, 'depth': 5, 'learning_rate': 0.04333847082132899}. Best is trial 66 with value: 0.2597385582056418.
[I 2026-02-17 08:35:43,295] Trial 67 finished with value: 0.26253142398081114 and parameters: {'iterations': 296, 'depth': 4, 'learning_rate': 0.06265221846524055}. Best is trial 66 with value: 0.2597385582056418.
[I 2026-02-17 08:35:50,390] Trial 68 finished with value: 0.27752444061469655 and parameters: {'iterations': 264, 'depth': 9, 'learning_rate': 0.0815781450875168}. Best is trial 66 with value: 0.2597385582056418.
[I 2026-02-17 08:35:51,902] Trial 69 finished with value: 0.2654857497870363 and parameters: {'iterations': 309, 'depth': 6, 'learning_rate': 0.04719260215006044}. Best is trial 66 with value: 0.2597385582056418.
[I 2026-02-17 08:35:52,987] Trial 70 finished with value: 0.25986848636574333 and parameters: {'iterations': 322, 'depth': 5, 'learning_rate': 0.040466607659129655}. Best is trial 66 with value: 0.2597385582056418.
[I 2026-02-17 08:35:54,051] Trial 71 finished with value: 0.2590026920010341 and parameters: {'iterations': 322, 'depth': 5, 'learning_rate': 0.04013607342655292}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:35:55,128] Trial 72 finished with value: 0.2603468158538499 and parameters: {'iterations': 325, 'depth': 5, 'learning_rate': 0.04139027998632175}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:35:56,203] Trial 73 finished with value: 0.2602909869403657 and parameters: {'iterations': 321, 'depth': 5, 'learning_rate': 0.041722850433422706}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:35:57,841] Trial 74 finished with value: 0.2640959185876987 and parameters: {'iterations': 323, 'depth': 6, 'learning_rate': 0.04060106060528382}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:35:58,811] Trial 75 finished with value: 0.2632027314159613 and parameters: {'iterations': 284, 'depth': 5, 'learning_rate': 0.06568955587279394}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:00,635] Trial 76 finished with value: 0.26916847712030983 and parameters: {'iterations': 298, 'depth': 5, 'learning_rate': 0.11548935557635201}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:01,793] Trial 77 finished with value: 0.26441291991045734 and parameters: {'iterations': 231, 'depth': 6, 'learning_rate': 0.03355215884692538}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:02,848] Trial 78 finished with value: 0.2601557252914316 and parameters: {'iterations': 317, 'depth': 5, 'learning_rate': 0.042775499887546975}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:03,983] Trial 79 finished with value: 0.2666755969174226 and parameters: {'iterations': 344, 'depth': 5, 'learning_rate': 0.09084646551461638}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:05,513] Trial 80 finished with value: 0.26526383553671085 and parameters: {'iterations': 314, 'depth': 6, 'learning_rate': 0.04572505481678709}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:06,685] Trial 81 finished with value: 0.25900627167797696 and parameters: {'iterations': 365, 'depth': 5, 'learning_rate': 0.03773561430412548}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:07,898] Trial 82 finished with value: 0.265627861361323 and parameters: {'iterations': 365, 'depth': 5, 'learning_rate': 0.058202524660195196}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:13,230] Trial 83 finished with value: 0.26628460372910523 and parameters: {'iterations': 356, 'depth': 8, 'learning_rate': 0.03596530296675534}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:14,247] Trial 84 finished with value: 0.2609775856467928 and parameters: {'iterations': 301, 'depth': 5, 'learning_rate': 0.05047920515904623}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:15,386] Trial 85 finished with value: 0.2730741532893825 and parameters: {'iterations': 335, 'depth': 5, 'learning_rate': 0.13802348738745715}. Best is trial 71 with value: 0.2590026920010341.
[I 2026-02-17 08:36:16,377] Trial 86 finished with value: 0.2587230304278461 and parameters: {'iterations': 288, 'depth': 5, 'learning_rate': 0.040123970161807035}. Best is trial 86 with value: 0.2587230304278461.
[I 2026-02-17 08:36:17,342] Trial 87 finished with value: 0.26013430942764076 and parameters: {'iterations': 281, 'depth': 5, 'learning_rate': 0.032588504146919044}. Best is trial 86 with value: 0.2587230304278461.
[I 2026-02-17 08:36:18,738] Trial 88 finished with value: 0.2631269335153494 and parameters: {'iterations': 280, 'depth': 6, 'learning_rate': 0.03087482988548007}. Best is trial 86 with value: 0.2587230304278461.
[I 2026-02-17 08:36:19,690] Trial 89 finished with value: 0.2639291825860235 and parameters: {'iterations': 271, 'depth': 5, 'learning_rate': 0.05487689319382542}. Best is trial 86 with value: 0.2587230304278461.
[I 2026-02-17 08:36:20,328] Trial 90 finished with value: 0.2615227604484226 and parameters: {'iterations': 241, 'depth': 4, 'learning_rate': 0.037802011302239015}. Best is trial 86 with value: 0.2587230304278461.
[I 2026-02-17 08:36:21,276] Trial 91 finished with value: 0.2614419882372296 and parameters: {'iterations': 282, 'depth': 5, 'learning_rate': 0.02785420865925593}. Best is trial 86 with value: 0.2587230304278461.
[I 2026-02-17 08:36:22,876] Trial 92 finished with value: 0.2590630870015096 and parameters: {'iterations': 293, 'depth': 5, 'learning_rate': 0.0334893851862471}. Best is trial 86 with value: 0.2587230304278461.

CatBoost best RMSE: 0.2587230304278461
{'iterations': 288, 'depth': 5, 'learning_rate': 0.040123970161807035}

In [ ]:
from sklearn.ensemble import HistGradientBoostingRegressor

def objective_hgb(trial):

    params = {
        "max_iter": trial.suggest_int("max_iter", 100, 400),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "random_state": 42
    }

    model = HistGradientBoostingRegressor(**params)

    scores = cross_val_score(
        model, X, y,
        cv=kf,
        scoring="neg_root_mean_squared_error"
    )

    return -scores.mean()

In [ ]:
study_hgb = optuna.create_study(direction="minimize")
study_hgb.optimize(objective_hgb, n_trials=100)

print("HistGB best RMSE:", study_hgb.best_value)
print(study_hgb.best_params)

[I 2026-02-17 08:36:29,545] A new study created in memory with name: no-name-d86d1d82-5e20-4aa0-b88f-51a55cd4d059
[I 2026-02-17 08:36:30,300] Trial 0 finished with value: 0.2768772252266446 and parameters: {'max_iter': 209, 'learning_rate': 0.024154838934651587, 'max_depth': 6}. Best is trial 0 with value: 0.2768772252266446.
[I 2026-02-17 08:36:31,508] Trial 1 finished with value: 0.30118248776116646 and parameters: {'max_iter': 347, 'learning_rate': 0.14240121984732884, 'max_depth': 8}. Best is trial 0 with value: 0.2768772252266446.
[I 2026-02-17 08:36:32,137] Trial 2 finished with value: 0.27943912854905617 and parameters: {'max_iter': 358, 'learning_rate': 0.1409034058683209, 'max_depth': 3}. Best is trial 0 with value: 0.2768772252266446.
[I 2026-02-17 08:36:33,033] Trial 3 finished with value: 0.29913000808741574 and parameters: {'max_iter': 373, 'learning_rate': 0.16138391583153616, 'max_depth': 5}. Best is trial 0 with value: 0.2768772252266446.
[I 2026-02-17 08:36:33,334] Trial 4 finished with value: 0.2753355859331773 and parameters: {'max_iter': 114, 'learning_rate': 0.165806939749222, 'max_depth': 3}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:35,161] Trial 5 finished with value: 0.29928368934448213 and parameters: {'max_iter': 356, 'learning_rate': 0.15316945636648138, 'max_depth': 9}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:36,204] Trial 6 finished with value: 0.2846368733284049 and parameters: {'max_iter': 255, 'learning_rate': 0.06397547442885607, 'max_depth': 10}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:36,644] Trial 7 finished with value: 0.2828480435907258 and parameters: {'max_iter': 200, 'learning_rate': 0.16462382023667646, 'max_depth': 4}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:37,272] Trial 8 finished with value: 0.28492990608669067 and parameters: {'max_iter': 171, 'learning_rate': 0.10439385440983014, 'max_depth': 8}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:38,336] Trial 9 finished with value: 0.28406178775182334 and parameters: {'max_iter': 272, 'learning_rate': 0.06051638042210417, 'max_depth': 9}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:38,672] Trial 10 finished with value: 0.2845115420289487 and parameters: {'max_iter': 102, 'learning_rate': 0.1963453780300064, 'max_depth': 6}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:39,134] Trial 11 finished with value: 0.2875390294250357 and parameters: {'max_iter': 100, 'learning_rate': 0.024134051853974502, 'max_depth': 12}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:39,875] Trial 12 finished with value: 0.2936029305586281 and parameters: {'max_iter': 173, 'learning_rate': 0.012582244033208345, 'max_depth': 6}. Best is trial 4 with value: 0.2753355859331773.
[I 2026-02-17 08:36:40,250] Trial 13 finished with value: 0.275275740525267 and parameters: {'max_iter': 215, 'learning_rate': 0.10112332018464416, 'max_depth': 3}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:40,750] Trial 14 finished with value: 0.27743526508500094 and parameters: {'max_iter': 297, 'learning_rate': 0.1078746429948794, 'max_depth': 3}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:41,074] Trial 15 finished with value: 0.2771797564947124 and parameters: {'max_iter': 133, 'learning_rate': 0.10812708960948755, 'max_depth': 4}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:41,458] Trial 16 finished with value: 0.28076164628005246 and parameters: {'max_iter': 223, 'learning_rate': 0.1986488586829681, 'max_depth': 3}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:41,884] Trial 17 finished with value: 0.277266401265493 and parameters: {'max_iter': 151, 'learning_rate': 0.0811316222880582, 'max_depth': 5}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:42,557] Trial 18 finished with value: 0.2865014161101528 and parameters: {'max_iter': 313, 'learning_rate': 0.13103246479425174, 'max_depth': 4}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:43,576] Trial 19 finished with value: 0.29576446209537777 and parameters: {'max_iter': 233, 'learning_rate': 0.17340309340649773, 'max_depth': 12}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:44,041] Trial 20 finished with value: 0.28614640791144097 and parameters: {'max_iter': 133, 'learning_rate': 0.12268727953755953, 'max_depth': 7}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:44,632] Trial 21 finished with value: 0.27691990003712597 and parameters: {'max_iter': 209, 'learning_rate': 0.04453434042701813, 'max_depth': 5}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:45,491] Trial 22 finished with value: 0.2811536893238806 and parameters: {'max_iter': 187, 'learning_rate': 0.08489629195889599, 'max_depth': 6}. Best is trial 13 with value: 0.275275740525267.
[I 2026-02-17 08:36:46,199] Trial 23 finished with value: 0.2745761628280098 and parameters: {'max_iter': 250, 'learning_rate': 0.03638907057369803, 'max_depth': 3}. Best is trial 23 with value: 0.2745761628280098.
[I 2026-02-17 08:36:46,702] Trial 24 finished with value: 0.2743227770757226 and parameters: {'max_iter': 279, 'learning_rate': 0.04359666459954184, 'max_depth': 3}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:47,327] Trial 25 finished with value: 0.27719681108685856 and parameters: {'max_iter': 289, 'learning_rate': 0.0657952291461468, 'max_depth': 4}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:47,802] Trial 26 finished with value: 0.2745981068987578 and parameters: {'max_iter': 253, 'learning_rate': 0.046085735949193254, 'max_depth': 3}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:48,369] Trial 27 finished with value: 0.275517154650326 and parameters: {'max_iter': 248, 'learning_rate': 0.04157763547145547, 'max_depth': 4}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:49,216] Trial 28 finished with value: 0.2775188588425235 and parameters: {'max_iter': 321, 'learning_rate': 0.044332339277674916, 'max_depth': 5}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:49,723] Trial 29 finished with value: 0.2760966235359319 and parameters: {'max_iter': 274, 'learning_rate': 0.02473329972895861, 'max_depth': 3}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:50,336] Trial 30 finished with value: 0.2760116623977785 and parameters: {'max_iter': 248, 'learning_rate': 0.036991620444619164, 'max_depth': 4}. Best is trial 24 with value: 0.2743227770757226.
[I 2026-02-17 08:36:50,741] Trial 31 finished with value: 0.27396546689382906 and parameters: {'max_iter': 225, 'learning_rate': 0.08692214283454179, 'max_depth': 3}. Best is trial 31 with value: 0.27396546689382906.
[I 2026-02-17 08:36:51,220] Trial 32 finished with value: 0.27407389600083487 and parameters: {'max_iter': 268, 'learning_rate': 0.0832525970290234, 'max_depth': 3}. Best is trial 31 with value: 0.27396546689382906.
[I 2026-02-17 08:36:51,897] Trial 33 finished with value: 0.27907416385594475 and parameters: {'max_iter': 320, 'learning_rate': 0.08837791517773515, 'max_depth': 4}. Best is trial 31 with value: 0.27396546689382906.
[I 2026-02-17 08:36:52,597] Trial 34 finished with value: 0.2796343235378863 and parameters: {'max_iter': 270, 'learning_rate': 0.05659864462418426, 'max_depth': 5}. Best is trial 31 with value: 0.27396546689382906.
[I 2026-02-17 08:36:53,017] Trial 35 finished with value: 0.2738903944371348 and parameters: {'max_iter': 231, 'learning_rate': 0.07207429247791884, 'max_depth': 3}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:54,221] Trial 36 finished with value: 0.2915058215742427 and parameters: {'max_iter': 392, 'learning_rate': 0.07440798762149917, 'max_depth': 7}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:54,617] Trial 37 finished with value: 0.2751610819996032 and parameters: {'max_iter': 233, 'learning_rate': 0.09619338363366492, 'max_depth': 3}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:55,337] Trial 38 finished with value: 0.27993059930743813 and parameters: {'max_iter': 342, 'learning_rate': 0.07973601394393381, 'max_depth': 4}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:56,833] Trial 39 finished with value: 0.2862945599275567 and parameters: {'max_iter': 295, 'learning_rate': 0.06914796875319618, 'max_depth': 11}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:57,647] Trial 40 finished with value: 0.280888253130701 and parameters: {'max_iter': 191, 'learning_rate': 0.09346716285147848, 'max_depth': 5}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:58,068] Trial 41 finished with value: 0.2744910408099573 and parameters: {'max_iter': 234, 'learning_rate': 0.05278203729084838, 'max_depth': 3}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:58,542] Trial 42 finished with value: 0.27483116425144705 and parameters: {'max_iter': 269, 'learning_rate': 0.054794345844071314, 'max_depth': 3}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:58,943] Trial 43 finished with value: 0.2740365732522773 and parameters: {'max_iter': 232, 'learning_rate': 0.07380413044040349, 'max_depth': 3}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:59,452] Trial 44 finished with value: 0.28084731563181753 and parameters: {'max_iter': 225, 'learning_rate': 0.11694993759502403, 'max_depth': 4}. Best is trial 35 with value: 0.2738903944371348.
[I 2026-02-17 08:36:59,806] Trial 45 finished with value: 0.27338123527725305 and parameters: {'max_iter': 201, 'learning_rate': 0.07198430216046856, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:00,610] Trial 46 finished with value: 0.28211486005314573 and parameters: {'max_iter': 201, 'learning_rate': 0.07392768120532313, 'max_depth': 9}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:00,928] Trial 47 finished with value: 0.27399436847683634 and parameters: {'max_iter': 175, 'learning_rate': 0.07380452447615611, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:01,418] Trial 48 finished with value: 0.2778769325908383 and parameters: {'max_iter': 170, 'learning_rate': 0.06434058801941163, 'max_depth': 5}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:01,771] Trial 49 finished with value: 0.27582610501979454 and parameters: {'max_iter': 157, 'learning_rate': 0.0943312649360638, 'max_depth': 4}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:02,486] Trial 50 finished with value: 0.28116359069683106 and parameters: {'max_iter': 186, 'learning_rate': 0.0746761163690719, 'max_depth': 8}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:02,856] Trial 51 finished with value: 0.2738240591538323 and parameters: {'max_iter': 210, 'learning_rate': 0.08562294817205685, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:03,206] Trial 52 finished with value: 0.27504079744763105 and parameters: {'max_iter': 195, 'learning_rate': 0.10221625640493774, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:03,688] Trial 53 finished with value: 0.27591456224417865 and parameters: {'max_iter': 213, 'learning_rate': 0.08995937972864002, 'max_depth': 4}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:04,019] Trial 54 finished with value: 0.2744497536005426 and parameters: {'max_iter': 176, 'learning_rate': 0.06978582339091872, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:04,393] Trial 55 finished with value: 0.2741573470447568 and parameters: {'max_iter': 209, 'learning_rate': 0.11338880699357884, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:04,875] Trial 56 finished with value: 0.2777249292535894 and parameters: {'max_iter': 222, 'learning_rate': 0.08006926115862434, 'max_depth': 4}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:05,500] Trial 57 finished with value: 0.2778077499304692 and parameters: {'max_iter': 142, 'learning_rate': 0.060454488642049165, 'max_depth': 10}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:05,918] Trial 58 finished with value: 0.27461122102103636 and parameters: {'max_iter': 238, 'learning_rate': 0.07649235272129079, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:06,296] Trial 59 finished with value: 0.27947757900032294 and parameters: {'max_iter': 163, 'learning_rate': 0.09838531893935162, 'max_depth': 4}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:06,676] Trial 60 finished with value: 0.2749435153938898 and parameters: {'max_iter': 202, 'learning_rate': 0.08644508840688495, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:07,125] Trial 61 finished with value: 0.27394348093816295 and parameters: {'max_iter': 259, 'learning_rate': 0.08324350087845704, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:07,535] Trial 62 finished with value: 0.27460012665651046 and parameters: {'max_iter': 222, 'learning_rate': 0.06406749036720857, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:08,122] Trial 63 finished with value: 0.2785911394972506 and parameters: {'max_iter': 180, 'learning_rate': 0.10717939182831207, 'max_depth': 4}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:08,760] Trial 64 finished with value: 0.27577954367107604 and parameters: {'max_iter': 244, 'learning_rate': 0.07023693508311955, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:09,318] Trial 65 finished with value: 0.2758716342304654 and parameters: {'max_iter': 262, 'learning_rate': 0.09061207183558209, 'max_depth': 3}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:09,905] Trial 66 finished with value: 0.2765982910922492 and parameters: {'max_iter': 261, 'learning_rate': 0.051036601007312055, 'max_depth': 4}. Best is trial 45 with value: 0.27338123527725305.
[I 2026-02-17 08:37:10,299] Trial 67 finished with value: 0.2730448128473745 and parameters: {'max_iter': 216, 'learning_rate': 0.0837610953066862, 'max_depth': 3}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:10,850] Trial 68 finished with value: 0.2855181108903938 and parameters: {'max_iter': 207, 'learning_rate': 0.13700054922520952, 'max_depth': 5}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:11,338] Trial 69 finished with value: 0.2777593412666116 and parameters: {'max_iter': 216, 'learning_rate': 0.08348243740012191, 'max_depth': 4}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:11,743] Trial 70 finished with value: 0.2784003174371119 and parameters: {'max_iter': 116, 'learning_rate': 0.10085795793295277, 'max_depth': 6}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:12,153] Trial 71 finished with value: 0.27378670901831614 and parameters: {'max_iter': 227, 'learning_rate': 0.07822536536341286, 'max_depth': 3}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:12,510] Trial 72 finished with value: 0.2744566000419183 and parameters: {'max_iter': 195, 'learning_rate': 0.07924338353604812, 'max_depth': 3}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:12,965] Trial 73 finished with value: 0.2735280514142124 and parameters: {'max_iter': 240, 'learning_rate': 0.06161011014896945, 'max_depth': 3}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:13,455] Trial 74 finished with value: 0.27384421323380737 and parameters: {'max_iter': 284, 'learning_rate': 0.05940976293156945, 'max_depth': 3}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:14,000] Trial 75 finished with value: 0.2777000101065381 and parameters: {'max_iter': 242, 'learning_rate': 0.06273178148452725, 'max_depth': 4}. Best is trial 67 with value: 0.2730448128473745.
[I 2026-02-17 08:37:14,489] Trial 76 finished with value: 0.27289354413374256 and parameters: {'max_iter': 284, 'learning_rate': 0.05920846149929694, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:15,053] Trial 77 finished with value: 0.27539869369773057 and parameters: {'max_iter': 307, 'learning_rate': 0.0299680716455292, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:15,664] Trial 78 finished with value: 0.27776678698234053 and parameters: {'max_iter': 287, 'learning_rate': 0.058666376021588515, 'max_depth': 4}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:16,173] Trial 79 finished with value: 0.27370367465045786 and parameters: {'max_iter': 280, 'learning_rate': 0.0489740000837525, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:17,359] Trial 80 finished with value: 0.2795030761951007 and parameters: {'max_iter': 285, 'learning_rate': 0.011163883983231579, 'max_depth': 7}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:17,914] Trial 81 finished with value: 0.27450866771057303 and parameters: {'max_iter': 304, 'learning_rate': 0.04920099022247191, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:18,462] Trial 82 finished with value: 0.2754423220192298 and parameters: {'max_iter': 327, 'learning_rate': 0.06727313982440372, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:18,960] Trial 83 finished with value: 0.2749843533128046 and parameters: {'max_iter': 276, 'learning_rate': 0.03888563172481232, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:19,695] Trial 84 finished with value: 0.27418145120391696 and parameters: {'max_iter': 296, 'learning_rate': 0.04806737600256686, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:20,611] Trial 85 finished with value: 0.27813920393824615 and parameters: {'max_iter': 282, 'learning_rate': 0.05690996962577166, 'max_depth': 4}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:21,107] Trial 86 finished with value: 0.2752013606100304 and parameters: {'max_iter': 254, 'learning_rate': 0.0309854343665511, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:21,591] Trial 87 finished with value: 0.2835664191382242 and parameters: {'max_iter': 231, 'learning_rate': 0.18166033133099435, 'max_depth': 4}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:21,979] Trial 88 finished with value: 0.2756865791797325 and parameters: {'max_iter': 217, 'learning_rate': 0.054674249467305855, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:22,514] Trial 89 finished with value: 0.27646059674938156 and parameters: {'max_iter': 241, 'learning_rate': 0.06528101027661332, 'max_depth': 4}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:22,905] Trial 90 finished with value: 0.2767488021413682 and parameters: {'max_iter': 226, 'learning_rate': 0.1522887982925693, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.
[I 2026-02-17 08:37:23,372] Trial 91 finished with value: 0.2744091964966807 and parameters: {'max_iter': 259, 'learning_rate': 0.07017322971706608, 'max_depth': 3}. Best is trial 76 with value: 0.27289354413374256.

HistGB best RMSE: 0.27289354413374256
{'max_iter': 284, 'learning_rate': 0.05920846149929694, 'max_depth': 3}

In [ ]:
from sklearn.ensemble import RandomForestRegressor

def objective_rf(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 25),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "random_state": 42
    }

    model = RandomForestRegressor(**params)

    scores = cross_val_score(
        model, X, y,
        cv=kf,
        scoring="neg_root_mean_squared_error"
    )

    return -scores.mean()

In [ ]:
study_rf = optuna.create_study(direction="minimize")
study_rf.optimize(objective_rf, n_trials=100)

print("Random Forest best RMSE:", study_rf.best_value)
print(study_rf.best_params)

[I 2026-02-17 08:37:27,191] A new study created in memory with name: no-name-91a8b7d1-2dc9-417f-9c9f-183184afdd76
[I 2026-02-17 08:37:28,384] Trial 0 finished with value: 0.27777454493943615 and parameters: {'n_estimators': 133, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 0 with value: 0.27777454493943615.
[I 2026-02-17 08:37:31,310] Trial 1 finished with value: 0.2754679546797669 and parameters: {'n_estimators': 276, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:34,984] Trial 2 finished with value: 0.2784871928242947 and parameters: {'n_estimators': 322, 'max_depth': 18, 'min_samples_split': 7}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:36,891] Trial 3 finished with value: 0.3194125790277993 and parameters: {'n_estimators': 289, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:38,928] Trial 4 finished with value: 0.2789376502106151 and parameters: {'n_estimators': 198, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:41,864] Trial 5 finished with value: 0.27577514307098794 and parameters: {'n_estimators': 309, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:46,329] Trial 6 finished with value: 0.2786296187522984 and parameters: {'n_estimators': 395, 'max_depth': 20, 'min_samples_split': 10}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:48,443] Trial 7 finished with value: 0.28001458654201505 and parameters: {'n_estimators': 256, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:50,277] Trial 8 finished with value: 0.2790039607866225 and parameters: {'n_estimators': 174, 'max_depth': 17, 'min_samples_split': 9}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:51,370] Trial 9 finished with value: 0.278700779000768 and parameters: {'n_estimators': 123, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:37:56,709] Trial 10 finished with value: 0.2772209908457806 and parameters: {'n_estimators': 385, 'max_depth': 25, 'min_samples_split': 2}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:00,551] Trial 11 finished with value: 0.27725620569327114 and parameters: {'n_estimators': 317, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:03,262] Trial 12 finished with value: 0.2766547942209533 and parameters: {'n_estimators': 241, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:07,445] Trial 13 finished with value: 0.27643690844678637 and parameters: {'n_estimators': 339, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:10,123] Trial 14 finished with value: 0.2764917933772325 and parameters: {'n_estimators': 252, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:14,580] Trial 15 finished with value: 0.2772424121811582 and parameters: {'n_estimators': 352, 'max_depth': 14, 'min_samples_split': 2}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:16,693] Trial 16 finished with value: 0.31926271312929866 and parameters: {'n_estimators': 285, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 1 with value: 0.2754679546797669.
[I 2026-02-17 08:38:18,932] Trial 17 finished with value: 0.2751519077932715 and parameters: {'n_estimators': 204, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:21,399] Trial 18 finished with value: 0.27688375823694045 and parameters: {'n_estimators': 211, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:23,351] Trial 19 finished with value: 0.27793073034484583 and parameters: {'n_estimators': 171, 'max_depth': 14, 'min_samples_split': 5}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:25,700] Trial 20 finished with value: 0.27532144106760037 and parameters: {'n_estimators': 228, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:28,242] Trial 21 finished with value: 0.2752785328288122 and parameters: {'n_estimators': 222, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:30,694] Trial 22 finished with value: 0.2753928905940372 and parameters: {'n_estimators': 220, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:32,635] Trial 23 finished with value: 0.27812673232357943 and parameters: {'n_estimators': 168, 'max_depth': 12, 'min_samples_split': 4}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:34,314] Trial 24 finished with value: 0.289615860294855 and parameters: {'n_estimators': 230, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:36,664] Trial 25 finished with value: 0.27761424007208624 and parameters: {'n_estimators': 193, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:38,239] Trial 26 finished with value: 0.2775430909234802 and parameters: {'n_estimators': 148, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:40,282] Trial 27 finished with value: 0.2801949065763151 and parameters: {'n_estimators': 195, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:42,771] Trial 28 finished with value: 0.27768531431820365 and parameters: {'n_estimators': 252, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:43,791] Trial 29 finished with value: 0.2786219571987606 and parameters: {'n_estimators': 111, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:46,775] Trial 30 finished with value: 0.2778696429209149 and parameters: {'n_estimators': 272, 'max_depth': 22, 'min_samples_split': 6}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:49,188] Trial 31 finished with value: 0.275377011164866 and parameters: {'n_estimators': 227, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 17 with value: 0.2751519077932715.
[I 2026-02-17 08:38:51,817] Trial 32 finished with value: 0.27502378330704635 and parameters: {'n_estimators': 226, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 32 with value: 0.27502378330704635.
[I 2026-02-17 08:38:53,674] Trial 33 finished with value: 0.27626692920384854 and parameters: {'n_estimators': 207, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 32 with value: 0.27502378330704635.
[I 2026-02-17 08:38:55,491] Trial 34 finished with value: 0.278286711438645 and parameters: {'n_estimators': 150, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 32 with value: 0.27502378330704635.
[I 2026-02-17 08:38:56,850] Trial 35 finished with value: 0.28948144167804346 and parameters: {'n_estimators': 183, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 32 with value: 0.27502378330704635.
[I 2026-02-17 08:38:59,891] Trial 36 finished with value: 0.27713693306013826 and parameters: {'n_estimators': 272, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 32 with value: 0.27502378330704635.
[I 2026-02-17 08:39:02,523] Trial 37 finished with value: 0.2751886101382981 and parameters: {'n_estimators': 234, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 32 with value: 0.27502378330704635.
[I 2026-02-17 08:39:04,660] Trial 38 finished with value: 0.2749460605503239 and parameters: {'n_estimators': 210, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:06,625] Trial 39 finished with value: 0.31958426417848845 and parameters: {'n_estimators': 300, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:07,811] Trial 40 finished with value: 0.28063057409633513 and parameters: {'n_estimators': 144, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:09,688] Trial 41 finished with value: 0.2763134211360107 and parameters: {'n_estimators': 211, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:12,009] Trial 42 finished with value: 0.27511574384043047 and parameters: {'n_estimators': 238, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:14,991] Trial 43 finished with value: 0.27561942485352725 and parameters: {'n_estimators': 262, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:17,280] Trial 44 finished with value: 0.27542659670123676 and parameters: {'n_estimators': 240, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:19,045] Trial 45 finished with value: 0.2903573084166515 and parameters: {'n_estimators': 240, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:21,260] Trial 46 finished with value: 0.276661140795405 and parameters: {'n_estimators': 181, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:23,516] Trial 47 finished with value: 0.2766270635976641 and parameters: {'n_estimators': 199, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:26,055] Trial 48 finished with value: 0.279925865653078 and parameters: {'n_estimators': 259, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:28,683] Trial 49 finished with value: 0.27640602277147963 and parameters: {'n_estimators': 238, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:30,695] Trial 50 finished with value: 0.2752575936603418 and parameters: {'n_estimators': 212, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:32,690] Trial 51 finished with value: 0.27708165639875104 and parameters: {'n_estimators': 215, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:34,132] Trial 52 finished with value: 0.276971603868657 and parameters: {'n_estimators': 162, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:36,128] Trial 53 finished with value: 0.27494957832567046 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:38,048] Trial 54 finished with value: 0.2797815513649534 and parameters: {'n_estimators': 199, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:40,595] Trial 55 finished with value: 0.2765093576204372 and parameters: {'n_estimators': 232, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:43,791] Trial 56 finished with value: 0.2770027264942031 and parameters: {'n_estimators': 285, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:46,081] Trial 57 finished with value: 0.2773981922876104 and parameters: {'n_estimators': 182, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:48,077] Trial 58 finished with value: 0.3194350260220919 and parameters: {'n_estimators': 247, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:50,472] Trial 59 finished with value: 0.2774030397389555 and parameters: {'n_estimators': 189, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:52,555] Trial 60 finished with value: 0.27529961544381853 and parameters: {'n_estimators': 204, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:54,656] Trial 61 finished with value: 0.27522939512968153 and parameters: {'n_estimators': 221, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:57,259] Trial 62 finished with value: 0.27744693333563863 and parameters: {'n_estimators': 220, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:39:58,819] Trial 63 finished with value: 0.2771786841231988 and parameters: {'n_estimators': 157, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:01,551] Trial 64 finished with value: 0.27561337804338826 and parameters: {'n_estimators': 234, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:03,964] Trial 65 finished with value: 0.27597213864084696 and parameters: {'n_estimators': 221, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:05,924] Trial 66 finished with value: 0.2899160878642061 and parameters: {'n_estimators': 265, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:08,328] Trial 67 finished with value: 0.2753040950588728 and parameters: {'n_estimators': 247, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:09,973] Trial 68 finished with value: 0.27692843450275095 and parameters: {'n_estimators': 175, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:12,685] Trial 69 finished with value: 0.27756273801786724 and parameters: {'n_estimators': 191, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:14,910] Trial 70 finished with value: 0.2751415880875314 and parameters: {'n_estimators': 225, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 38 with value: 0.2749460605503239.
[I 2026-02-17 08:40:16,905] Trial 71 finished with value: 0.2748580334744163 and parameters: {'n_estimators': 204, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:18,569] Trial 72 finished with value: 0.27954815000414174 and parameters: {'n_estimators': 201, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:20,581] Trial 73 finished with value: 0.2750082824729818 and parameters: {'n_estimators': 207, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:23,324] Trial 74 finished with value: 0.27648956213777665 and parameters: {'n_estimators': 208, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:25,300] Trial 75 finished with value: 0.2755645734799125 and parameters: {'n_estimators': 191, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:26,713] Trial 76 finished with value: 0.27989467474899393 and parameters: {'n_estimators': 173, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:28,249] Trial 77 finished with value: 0.2776259329355295 and parameters: {'n_estimators': 134, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:30,462] Trial 78 finished with value: 0.27502378330704635 and parameters: {'n_estimators': 226, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:33,040] Trial 79 finished with value: 0.2753941944607258 and parameters: {'n_estimators': 228, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:35,094] Trial 80 finished with value: 0.2897369338547392 and parameters: {'n_estimators': 246, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:37,152] Trial 81 finished with value: 0.2750532279051387 and parameters: {'n_estimators': 211, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:39,074] Trial 82 finished with value: 0.2762739112924772 and parameters: {'n_estimators': 215, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:41,076] Trial 83 finished with value: 0.27633927086802484 and parameters: {'n_estimators': 224, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:45,249] Trial 84 finished with value: 0.2756680372358942 and parameters: {'n_estimators': 361, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:47,734] Trial 85 finished with value: 0.27540026891066904 and parameters: {'n_estimators': 254, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:49,776] Trial 86 finished with value: 0.2761901801510819 and parameters: {'n_estimators': 186, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:51,870] Trial 87 finished with value: 0.27503067999645703 and parameters: {'n_estimators': 215, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:54,298] Trial 88 finished with value: 0.27676695327619266 and parameters: {'n_estimators': 204, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:56,667] Trial 89 finished with value: 0.27588989596658936 and parameters: {'n_estimators': 214, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:40:59,119] Trial 90 finished with value: 0.27561056672306716 and parameters: {'n_estimators': 235, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:41:01,017] Trial 91 finished with value: 0.27504693017767023 and parameters: {'n_estimators': 199, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:41:02,728] Trial 92 finished with value: 0.27648277560946816 and parameters: {'n_estimators': 194, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:41:04,757] Trial 93 finished with value: 0.27507696800975645 and parameters: {'n_estimators': 209, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:41:07,049] Trial 94 finished with value: 0.2762256385569066 and parameters: {'n_estimators': 197, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 71 with value: 0.2748580334744163.
[I 2026-02-17 08:41:08,942] Trial 95 finished with value: 0.27508296893173584 and parameters: {'n_estimators': 164, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 71 with value: 0.2748580334744163.

Random Forest best RMSE: 0.2748580334744163
{'n_estimators': 204, 'max_depth': 7, 'min_samples_split': 2}

In [ ]:
from xgboost import XGBRegressor

def objective_xgb(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "subsample": trial.suggest_float("subsample", 0.7, 1.0),
        "random_state": 42,
        "verbosity": 0
    }

    model = XGBRegressor(**params)

    scores = cross_val_score(
        model, X, y,
        cv=kf,
        scoring="neg_root_mean_squared_error"
    )

    return -scores.mean()

In [ ]:
study_xgb = optuna.create_study(direction="minimize")
study_xgb.optimize(objective_xgb, n_trials=100)

print("XGBoost best RMSE:", study_xgb.best_value)
print(study_xgb.best_params)

[I 2026-02-17 08:41:16,950] A new study created in memory with name: no-name-2a032480-a165-4d77-abd6-892873193ef3
[I 2026-02-17 08:41:17,163] Trial 0 finished with value: 0.27695564662196237 and parameters: {'n_estimators': 165, 'max_depth': 3, 'learning_rate': 0.14978586627555793, 'subsample': 0.8505917459826577}. Best is trial 0 with value: 0.27695564662196237.
[I 2026-02-17 08:41:19,462] Trial 1 finished with value: 0.29275668246206427 and parameters: {'n_estimators': 190, 'max_depth': 9, 'learning_rate': 0.0781956709813772, 'subsample': 0.9688819851896169}. Best is trial 0 with value: 0.27695564662196237.
[I 2026-02-17 08:41:19,899] Trial 2 finished with value: 0.2733251545400694 and parameters: {'n_estimators': 257, 'max_depth': 3, 'learning_rate': 0.11971495247438312, 'subsample': 0.9135613305690652}. Best is trial 2 with value: 0.2733251545400694.
[I 2026-02-17 08:41:20,776] Trial 3 finished with value: 0.28767165917359894 and parameters: {'n_estimators': 151, 'max_depth': 8, 'learning_rate': 0.04381369014265311, 'subsample': 0.9195058548583519}. Best is trial 2 with value: 0.2733251545400694.
[I 2026-02-17 08:41:22,253] Trial 4 finished with value: 0.2827434359840372 and parameters: {'n_estimators': 360, 'max_depth': 7, 'learning_rate': 0.03886218558577577, 'subsample': 0.8826177356802682}. Best is trial 2 with value: 0.2733251545400694.
[I 2026-02-17 08:41:22,407] Trial 5 finished with value: 0.2754601174790353 and parameters: {'n_estimators': 110, 'max_depth': 3, 'learning_rate': 0.15898603847158146, 'subsample': 0.9982982065810588}. Best is trial 2 with value: 0.2733251545400694.
[I 2026-02-17 08:41:22,752] Trial 6 finished with value: 0.2714843877314329 and parameters: {'n_estimators': 189, 'max_depth': 4, 'learning_rate': 0.032086495715950424, 'subsample': 0.9119307670483301}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:24,063] Trial 7 finished with value: 0.28474579294242164 and parameters: {'n_estimators': 322, 'max_depth': 7, 'learning_rate': 0.08550441727072225, 'subsample': 0.9792918047260695}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:26,295] Trial 8 finished with value: 0.28330671537011903 and parameters: {'n_estimators': 309, 'max_depth': 10, 'learning_rate': 0.05341465250371955, 'subsample': 0.7397421266572559}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:26,534] Trial 9 finished with value: 0.2723233427393431 and parameters: {'n_estimators': 132, 'max_depth': 4, 'learning_rate': 0.10825589080321492, 'subsample': 0.703283244291207}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:27,130] Trial 10 finished with value: 0.2886366642992456 and parameters: {'n_estimators': 217, 'max_depth': 5, 'learning_rate': 0.011044903040890005, 'subsample': 0.77501462422773}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:27,396] Trial 11 finished with value: 0.28186981953295814 and parameters: {'n_estimators': 104, 'max_depth': 5, 'learning_rate': 0.19685249140468314, 'subsample': 0.7968985285306895}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:28,005] Trial 12 finished with value: 0.2755368233953946 and parameters: {'n_estimators': 259, 'max_depth': 5, 'learning_rate': 0.11826569349888938, 'subsample': 0.7214839793148703}. Best is trial 6 with value: 0.2714843877314329.
[I 2026-02-17 08:41:28,297] Trial 13 finished with value: 0.26996710535328805 and parameters: {'n_estimators': 147, 'max_depth': 4, 'learning_rate': 0.09008060892016333, 'subsample': 0.8265450103910814}. Best is trial 13 with value: 0.26996710535328805.
[I 2026-02-17 08:41:29,070] Trial 14 finished with value: 0.29216419816509315 and parameters: {'n_estimators': 210, 'max_depth': 6, 'learning_rate': 0.011278130540307216, 'subsample': 0.8215859346662118}. Best is trial 13 with value: 0.26996710535328805.
[I 2026-02-17 08:41:29,415] Trial 15 finished with value: 0.2694849429976902 and parameters: {'n_estimators': 182, 'max_depth': 4, 'learning_rate': 0.0707962340067087, 'subsample': 0.8628454769646962}. Best is trial 15 with value: 0.2694849429976902.
[I 2026-02-17 08:41:31,147] Trial 16 finished with value: 0.2789747426348912 and parameters: {'n_estimators': 225, 'max_depth': 6, 'learning_rate': 0.08499273539745757, 'subsample': 0.8537172312039107}. Best is trial 15 with value: 0.2694849429976902.
[I 2026-02-17 08:41:31,575] Trial 17 finished with value: 0.2672483591982192 and parameters: {'n_estimators': 160, 'max_depth': 4, 'learning_rate': 0.0664074108440855, 'subsample': 0.8124053111601499}. Best is trial 17 with value: 0.2672483591982192.
[I 2026-02-17 08:41:31,891] Trial 18 finished with value: 0.2681175197643162 and parameters: {'n_estimators': 176, 'max_depth': 4, 'learning_rate': 0.05824534168595516, 'subsample': 0.778802905326878}. Best is trial 17 with value: 0.2672483591982192.
[I 2026-02-17 08:41:32,577] Trial 19 finished with value: 0.27514837352691385 and parameters: {'n_estimators': 294, 'max_depth': 5, 'learning_rate': 0.06260369625950547, 'subsample': 0.7580100552882869}. Best is trial 17 with value: 0.2672483591982192.
[I 2026-02-17 08:41:33,017] Trial 20 finished with value: 0.2820211352001433 and parameters: {'n_estimators': 134, 'max_depth': 6, 'learning_rate': 0.15058393591090025, 'subsample': 0.7872565603950065}. Best is trial 17 with value: 0.2672483591982192.
[I 2026-02-17 08:41:33,321] Trial 21 finished with value: 0.26706747861120017 and parameters: {'n_estimators': 175, 'max_depth': 4, 'learning_rate': 0.06616102155994315, 'subsample': 0.80831469919872}. Best is trial 21 with value: 0.26706747861120017.
[I 2026-02-17 08:41:33,574] Trial 22 finished with value: 0.26727946175847783 and parameters: {'n_estimators': 170, 'max_depth': 3, 'learning_rate': 0.05694761480228386, 'subsample': 0.8141299239931746}. Best is trial 21 with value: 0.26706747861120017.
[I 2026-02-17 08:41:33,871] Trial 23 finished with value: 0.2669543838293019 and parameters: {'n_estimators': 231, 'max_depth': 3, 'learning_rate': 0.02814821668816498, 'subsample': 0.818435644702212}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:34,156] Trial 24 finished with value: 0.2671561381649381 and parameters: {'n_estimators': 236, 'max_depth': 3, 'learning_rate': 0.02696387160873249, 'subsample': 0.8111410072886601}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:34,473] Trial 25 finished with value: 0.26811287634017866 and parameters: {'n_estimators': 238, 'max_depth': 3, 'learning_rate': 0.026279458486070606, 'subsample': 0.7462205473946832}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:34,824] Trial 26 finished with value: 0.2681192739689714 and parameters: {'n_estimators': 280, 'max_depth': 3, 'learning_rate': 0.023342402411361693, 'subsample': 0.8796624209850571}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:35,269] Trial 27 finished with value: 0.26801280081382645 and parameters: {'n_estimators': 389, 'max_depth': 3, 'learning_rate': 0.04391483792968973, 'subsample': 0.8424869790296475}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:35,783] Trial 28 finished with value: 0.27281927270027667 and parameters: {'n_estimators': 206, 'max_depth': 5, 'learning_rate': 0.02801985746647534, 'subsample': 0.8009546682128392}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:36,072] Trial 29 finished with value: 0.26756327510263667 and parameters: {'n_estimators': 239, 'max_depth': 3, 'learning_rate': 0.0974508777841692, 'subsample': 0.8321183147943851}. Best is trial 23 with value: 0.2669543838293019.
[I 2026-02-17 08:41:36,572] Trial 30 finished with value: 0.2667240583885038 and parameters: {'n_estimators': 276, 'max_depth': 4, 'learning_rate': 0.04760655988836371, 'subsample': 0.7651641448327788}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:37,021] Trial 31 finished with value: 0.26764573194518226 and parameters: {'n_estimators': 265, 'max_depth': 4, 'learning_rate': 0.04447995106314924, 'subsample': 0.7690471884440608}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:37,394] Trial 32 finished with value: 0.26718062516723856 and parameters: {'n_estimators': 326, 'max_depth': 3, 'learning_rate': 0.019938853283440944, 'subsample': 0.7985475234043626}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:37,890] Trial 33 finished with value: 0.2713832273396804 and parameters: {'n_estimators': 280, 'max_depth': 4, 'learning_rate': 0.07336112152283106, 'subsample': 0.7373010427123072}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:38,178] Trial 34 finished with value: 0.2689623331570249 and parameters: {'n_estimators': 242, 'max_depth': 3, 'learning_rate': 0.05036856961553038, 'subsample': 0.7638577845334149}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:40,002] Trial 35 finished with value: 0.2849386542095873 and parameters: {'n_estimators': 276, 'max_depth': 9, 'learning_rate': 0.03614813914720735, 'subsample': 0.8678915610406723}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:40,571] Trial 36 finished with value: 0.2730105950388334 and parameters: {'n_estimators': 230, 'max_depth': 5, 'learning_rate': 0.0185328473709299, 'subsample': 0.8923505783782572}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:42,656] Trial 37 finished with value: 0.27995590454402147 and parameters: {'n_estimators': 205, 'max_depth': 8, 'learning_rate': 0.03958236475067761, 'subsample': 0.7858902924210699}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:43,467] Trial 38 finished with value: 0.2748681887719312 and parameters: {'n_estimators': 345, 'max_depth': 4, 'learning_rate': 0.07824853847530508, 'subsample': 0.8471287369418748}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:43,716] Trial 39 finished with value: 0.2685718313379071 and parameters: {'n_estimators': 196, 'max_depth': 3, 'learning_rate': 0.03157772298747616, 'subsample': 0.9265688115819077}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:44,769] Trial 40 finished with value: 0.2777032474359041 and parameters: {'n_estimators': 252, 'max_depth': 7, 'learning_rate': 0.05028269350576179, 'subsample': 0.8330976530176524}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:45,176] Trial 41 finished with value: 0.2671154000669447 and parameters: {'n_estimators': 324, 'max_depth': 3, 'learning_rate': 0.020531268750569355, 'subsample': 0.7991747809412618}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:45,536] Trial 42 finished with value: 0.27494314967690175 and parameters: {'n_estimators': 305, 'max_depth': 3, 'learning_rate': 0.011264209723592909, 'subsample': 0.8074180379181577}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:46,108] Trial 43 finished with value: 0.2707020579179532 and parameters: {'n_estimators': 336, 'max_depth': 4, 'learning_rate': 0.03557845563173327, 'subsample': 0.7530042003036628}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:46,555] Trial 44 finished with value: 0.2799029125661413 and parameters: {'n_estimators': 377, 'max_depth': 3, 'learning_rate': 0.13275086217027796, 'subsample': 0.725438905502104}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:47,087] Trial 45 finished with value: 0.26707341799266787 and parameters: {'n_estimators': 294, 'max_depth': 4, 'learning_rate': 0.019812904195077523, 'subsample': 0.7906874833746367}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:47,798] Trial 46 finished with value: 0.27001723166675246 and parameters: {'n_estimators': 297, 'max_depth': 5, 'learning_rate': 0.018268781196747293, 'subsample': 0.7920896019526072}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:48,364] Trial 47 finished with value: 0.28577857333978096 and parameters: {'n_estimators': 317, 'max_depth': 4, 'learning_rate': 0.18661207050463047, 'subsample': 0.7760598217518628}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:48,963] Trial 48 finished with value: 0.27053403490985195 and parameters: {'n_estimators': 358, 'max_depth': 4, 'learning_rate': 0.04456398189297868, 'subsample': 0.8206550123142892}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:49,666] Trial 49 finished with value: 0.27019364800656775 and parameters: {'n_estimators': 287, 'max_depth': 5, 'learning_rate': 0.03391611096503089, 'subsample': 0.7657318773583868}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:50,139] Trial 50 finished with value: 0.2675907861048078 and parameters: {'n_estimators': 260, 'max_depth': 4, 'learning_rate': 0.017242598974270835, 'subsample': 0.7128376523036108}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:50,463] Trial 51 finished with value: 0.2673366568238656 and parameters: {'n_estimators': 271, 'max_depth': 3, 'learning_rate': 0.03029733484748441, 'subsample': 0.805388246840525}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:50,838] Trial 52 finished with value: 0.26702843448325225 and parameters: {'n_estimators': 315, 'max_depth': 3, 'learning_rate': 0.024095387558652228, 'subsample': 0.8332711897395615}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:51,240] Trial 53 finished with value: 0.2683709473106083 and parameters: {'n_estimators': 307, 'max_depth': 3, 'learning_rate': 0.05129772081283236, 'subsample': 0.8399001792923244}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:51,802] Trial 54 finished with value: 0.2671232410984017 and parameters: {'n_estimators': 339, 'max_depth': 4, 'learning_rate': 0.01417666960918261, 'subsample': 0.8550792821765155}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:52,358] Trial 55 finished with value: 0.27324241310439495 and parameters: {'n_estimators': 317, 'max_depth': 4, 'learning_rate': 0.06165229314853107, 'subsample': 0.8193789131514456}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:54,416] Trial 56 finished with value: 0.27484412370898437 and parameters: {'n_estimators': 354, 'max_depth': 6, 'learning_rate': 0.023442330615031166, 'subsample': 0.783920772149342}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:54,982] Trial 57 finished with value: 0.26825971242498736 and parameters: {'n_estimators': 330, 'max_depth': 3, 'learning_rate': 0.03940647318553768, 'subsample': 0.8283512793439781}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:55,199] Trial 58 finished with value: 0.2667844893204005 and parameters: {'n_estimators': 114, 'max_depth': 4, 'learning_rate': 0.06781236381222791, 'subsample': 0.8002265014947686}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:55,503] Trial 59 finished with value: 0.2690291987060533 and parameters: {'n_estimators': 112, 'max_depth': 5, 'learning_rate': 0.06868088426508728, 'subsample': 0.7754332611012743}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:56,747] Trial 60 finished with value: 0.29264094479418545 and parameters: {'n_estimators': 156, 'max_depth': 10, 'learning_rate': 0.09256344880919087, 'subsample': 0.9530021466602845}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:57,021] Trial 61 finished with value: 0.27095780043763656 and parameters: {'n_estimators': 141, 'max_depth': 4, 'learning_rate': 0.0809337467343585, 'subsample': 0.7938898866979491}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:57,250] Trial 62 finished with value: 0.2720341766409683 and parameters: {'n_estimators': 115, 'max_depth': 4, 'learning_rate': 0.10708803813708376, 'subsample': 0.8034010526282176}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:57,647] Trial 63 finished with value: 0.2682917208909311 and parameters: {'n_estimators': 299, 'max_depth': 3, 'learning_rate': 0.05557220084305679, 'subsample': 0.8183008654397999}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:57,911] Trial 64 finished with value: 0.2692153063487662 and parameters: {'n_estimators': 125, 'max_depth': 4, 'learning_rate': 0.04635999692214696, 'subsample': 0.8362063256085985}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:58,261] Trial 65 finished with value: 0.2671743077774858 and parameters: {'n_estimators': 289, 'max_depth': 3, 'learning_rate': 0.023498663241388943, 'subsample': 0.7546422903585612}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:58,716] Trial 66 finished with value: 0.27292964827844957 and parameters: {'n_estimators': 186, 'max_depth': 5, 'learning_rate': 0.06481796032955535, 'subsample': 0.7934630282355841}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:41:59,652] Trial 67 finished with value: 0.28735157877508744 and parameters: {'n_estimators': 170, 'max_depth': 8, 'learning_rate': 0.07285246210383729, 'subsample': 0.8637616869166467}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:42:00,088] Trial 68 finished with value: 0.2755449565915283 and parameters: {'n_estimators': 318, 'max_depth': 3, 'learning_rate': 0.1190168358485067, 'subsample': 0.7383903951028111}. Best is trial 30 with value: 0.2667240583885038.
[I 2026-02-17 08:42:00,464] Trial 69 finished with value: 0.26671250020013504 and parameters: {'n_estimators': 217, 'max_depth': 4, 'learning_rate': 0.0278818215279672, 'subsample': 0.810202675044814}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:01,014] Trial 70 finished with value: 0.2704584482120767 and parameters: {'n_estimators': 220, 'max_depth': 5, 'learning_rate': 0.03896808577354263, 'subsample': 0.8121220775678318}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:01,391] Trial 71 finished with value: 0.26753434498195794 and parameters: {'n_estimators': 215, 'max_depth': 4, 'learning_rate': 0.027577818190702586, 'subsample': 0.8252373846272527}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:01,878] Trial 72 finished with value: 0.2805413342047974 and parameters: {'n_estimators': 244, 'max_depth': 4, 'learning_rate': 0.010881943626136523, 'subsample': 0.7830869778349132}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:02,135] Trial 73 finished with value: 0.2699952738736576 and parameters: {'n_estimators': 198, 'max_depth': 3, 'learning_rate': 0.022373832221025573, 'subsample': 0.8009639824907291}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:02,530] Trial 74 finished with value: 0.26832347743499285 and parameters: {'n_estimators': 225, 'max_depth': 4, 'learning_rate': 0.034475763768029986, 'subsample': 0.768015241711462}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:02,878] Trial 75 finished with value: 0.26741436365485477 and parameters: {'n_estimators': 265, 'max_depth': 3, 'learning_rate': 0.04142485334648221, 'subsample': 0.8449564928484018}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:03,665] Trial 76 finished with value: 0.2755177412920699 and parameters: {'n_estimators': 252, 'max_depth': 6, 'learning_rate': 0.0290217890747481, 'subsample': 0.8539907701187598}. Best is trial 69 with value: 0.26671250020013504.
[I 2026-02-17 08:42:03,894] Trial 77 finished with value: 0.2663158495633472 and parameters: {'n_estimators': 148, 'max_depth': 3, 'learning_rate': 0.05785889525589491, 'subsample': 0.8106720032201505}. Best is trial 77 with value: 0.2663158495633472.

XGBoost best RMSE: 0.26573684771026046
{'n_estimators': 140, 'max_depth': 3, 'learning_rate': 0.07064044245116873, 'subsample': 0.7138101017422793}

In [ ]:
import pandas as pd

rmse_table = pd.DataFrame({
    "Model": [
        "Extra Trees",
        "CatBoost",
        "HistGradientBoosting",
        "Random Forest",
        "XGBoost"
    ],
    "Best RMSE (Optuna)": [
        study_et.best_value,
        study_cat.best_value,
        study_hgb.best_value,
        study_rf.best_value,
        study_xgb.best_value
    ]
})

rmse_table.sort_values("Best RMSE (Optuna)")

                  Model  Best RMSE (Optuna)
0           Extra Trees            0.258118
1              CatBoost            0.258723
4               XGBoost            0.265737
2  HistGradientBoosting            0.272894
3         Random Forest            0.274858

In [ ]:
best_et = ExtraTreesRegressor(
    **study_et.best_params,
    random_state=42,
    n_jobs=-1
)

best_et.fit(X, y)

ExtraTreesRegressor(max_depth=14, min_samples_split=10, n_estimators=293,
                    n_jobs=-1, random_state=42)

In [ ]:
import numpy as np

my_input = np.array([[
    420,   # class X obtained
    500,   # class X total
    450,   # class XII obtained
    78,    # diploma %
    12000, # entrance rank
    7.8,   # sem 1
    8.1,   # sem 2
    7.9    # sem 3
]])

# very important: same imputer
my_input = imputer.transform(my_input)

pred = best_et.predict(my_input)

print("Predicted SEM AVG :", pred[0])

Predicted SEM AVG : 7.957874583990666

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

In [ ]:
# check what features the model was trained on
X_train_columns = list(range(X.shape[1]))
print("Number of features:", X.shape[1])

Number of features: 8

Saving best model(extra trees regressor):

In [ ]:
import joblib

joblib.dump(best_et, "extra_trees_model.pkl")
joblib.dump(imputer, "imputer.pkl")

print("Model and imputer saved")

Model and imputer saved

**1**)Later (or in a new notebook) load and use it like this

import joblib

best_et = joblib.load("extra_trees_model.pkl")
imputer = joblib.load("imputer.pkl")

**2**) Then you can directly do:
my_input = pd.DataFrame([[
    420,
    500,
    450,
    78,
    12000,
    7.8,
    8.1,
    7.9
    **#marks**
]], columns=feature_cols)

my_input = imputer.transform(my_input)

pred = best_et.predict(my_input)

print(pred[0])